### ISSUE TITLE
miss URL

### ISSUE THREAD

**Issue by HasegawaTadamitsu** [sferik/twitter#1000]
I think miss url.404 not found.
correct?  http://sferik.github.com/twitter/

gem info twitter
> twitter (7.0.0)
>     Authors: Erik Michaels-Ober, John Nunemaker, Wynn Netherland, Steve
>     Richert, Steve Agalloco
>     Homepage: http://sferik.github.com/twitter/
>     License: MIT

and
https://rubygems.org/gems/twitter/versions/7.0.0
linked http://sferik.github.com/twitter//      correct?

**Comment by andypiper** [comment]
Correct. The page is http://sferik.github.io/twitter/
