### ISSUE TITLE
List add XX YY does not work

### ISSUE THREAD

**Issue by alexmelSC** [sferik/twitter#1006]
I install t using 'gem install' etc on the Mac. Authenticate using the twirl method and copy to .trc

t account is the right account
t timeline gives me my timeline
t follow works
t unfollow works

but when I run
t t list add big-list gem 
it fails with the following

_/usr/local/bin/t: Sorry, that page does not exist._

Interestingly list create XXX works

but list operations do not
Any idea what I can do?

---------
If you want to know a work around for unfollowing everyone similar to
t followings | xargs t list add following-`date "+%Y-%m-%d"`

then I just used Tweetdeck. 
1. Use t to get all you followings into a file t followers > foll.txt
2. then use split the file into 100 line chunks (limit of upload) split -l 100 roll.txt yy will get you a folder full of files yyaa yyab etc
3. open them and copy and paste via a tweetdecklist - see below.

https://mulley.ie/digital-marketing-and-social-media-guides-and-resources/how-to-mass-add-people-to-lists-on-twitter-2021-use-tweetdeck/

**Comment by sferik** [comment]
This sounds like a bug in `t`, not `twitter`. If you’re still having this issue, please feel free to open it [over there](https://github.com/sferik/t/issues/new).
