### ISSUE TITLE
Public metrics Support

### ISSUE THREAD

**Issue by wonderer007** [sferik/twitter#1012]
Does this gem support [public metrics](https://developer.twitter.com/en/docs/twitter-api/metrics) ?

https://developer.twitter.com/en/docs/twitter-api/metrics

Thank You

**Comment by andypiper** [comment]
I do not believe that the gem supports v2 of the API, there are other Ruby gems available e.g. [tweetkit](https://github.com/julianfssen/tweetkit). YMMV.
