### ISSUE TITLE
callback token is null

### ISSUE THREAD

**Issue by lujun525** [sferik/twitter#1014]
val twitterAuthClient = TwitterAuthClient()
        twitterAuthClient.authorize(
            this,
            object : Callback<TwitterSession>() {
                override fun success(result: Result<TwitterSession>) {
                    val authToken = result.data.authToken
                    val token = authToken.token
                }

                override fun failure(exception: TwitterException) {
                }
            })

As above，callback Some mobile phones authToken.token = null，How can we solve it

**Comment by andypiper** [comment]
If you’re talking about the recent Twitter for Android 9.54 release, try 9.54.1 which came out to fix that.
