### ISSUE TITLE
Could not authenticate you

### ISSUE THREAD

**Issue by jedis00** [sferik/twitter#1033]
I am not able to pull tweets via the API: Could not authenticate you

I've tripled checked the credentials used and they are correct.

Any ideas?

**Comment by moonlightz** [comment]
More likely that the app you registered is suspended. You can recreate the app to use v2 and oauth 1.0 but I think this project is not compatible yet with v2.

**Comment by jkotchoff** [comment]
You can use this technique with a different gem for the v2.0 twitter api:

https://gist.github.com/jkotchoff/e2f5e5fa431f090ab2fb62613287dfbb
