### ISSUE TITLE
The .user method returns a 403 forbidden and needs to be upgraded

### ISSUE THREAD

**Issue by sharkey11** [sferik/twitter#1035]
hi, when trying to call the `.user` function to lookup a user, like `.user("elonmusk")`, I get this error:

```
You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product (Twitter::Error::Forbidden)
```

I would love an update to the gem that updats it to v2. I used [this](https://gist.github.com/jkotchoff/e2f5e5fa431f090ab2fb62613287dfbb#file-2-one-off-rb) patch, but its very sus.

**Comment by hjoseph96** [comment]
Seconded.

**Comment by sferik** [comment]
For API 2, please checkout [X](https://github.com/sferik/x).
