### ISSUE TITLE
Changelog.md says minimum required version is 2.7.7

### ISSUE THREAD

**Issue by edgar-abadines** [sferik/twitter#1041]
If this is so, why does rubygems.org say that it requires Ruby >= 3.0?  Can this be dialed back so that software requiring Ruby 2.7.7 can use Twitter 8.0?

**Comment by sferik** [comment]
[Ruby 2.7 has an end-of-life status as of March 31, 2023.](https://www.ruby-lang.org/en/downloads/branches/) That means that known security issues will not be patched. I strongly recommend upgrading to Ruby 3.0 (or later), which was released on December 25, 2020. It is much more important for you to update to a newer Ruby version than to update to the latest version of the Twitter library.
