### ISSUE TITLE
Twitter.update and in_reply_to_status_id option

### ISSUE THREAD

**Issue by sawilde** [sferik/twitter#208]
Been trying to use the Twitter.update to update a status with a message whilst using the :in_reply_to_status_id parameter.

The update does not generate an error and I can see the tweet in the stream but when I check on the message using a call to http://api.twitter.com/1/statuses/show/XXXX.json the returning data shows null for the in_reply_to_status_id field.

Being new to RoR I am probably missing something obvious - can you help?

**Comment by peternixey** [comment]
@sawilde Shaun, did you manage to make this work. I have seen that you need to include the handle of the user in the tweet but even with that in place I can't get the tweet to show up as a reply...

**Comment by stve** [comment]
@peternixey you may want to refer to the discussion on #566 for some additional observations as to how this works.

**Comment by sawilde** [comment]
@peternixey - I believe so but after 3 years I no longer remember how nor do I still have access to that codebase.
