### ISSUE TITLE
Getting Twitter::Error::ClientError: execution expired

### ISSUE THREAD

**Issue by csph8** [sferik/twitter#401]
Getting this error Twitter::Error::ClientError: execution expired often & often

**Comment by nozpheratu** [comment]
I'm running into this issue seemingly only on my development host. My Twitter client is connecting just fine on my production servers, I connect with the exact same keys in production as I do in development.

Could twitter be blacklisting my IP?

**Comment by stve** [comment]
@nozpheratu are you streaming or are these REST requests? If you are streaming, the [following applies](https://dev.twitter.com/streaming/overview/connecting#connecting):

> A client establishes too many connections with the same credentials. When this occurs, the oldest connection will be terminated. This means you have to be careful not to run two reconnecting clients in parallel with the same credentials, or else they will take turns disconnecting each other.

Either way, I'd recommend using environment specific credentials.

**Comment by nozpheratu** [comment]
@stve These are REST requests. I'm trying to access `user_timeline` when the timeout occurs.
