### ISSUE TITLE
Twitter::Error::Unauthorized: Timestamp out of bounds

### ISSUE THREAD

**Issue by uranio-235** [sferik/twitter#403]
Twitter::Error::Unauthorized: Timestamp out of bounds
    from /usr/local/lib/ruby/gems/1.9.1/gems/twitter-4.6.2/lib/twitter/response/raise_error.rb:21:in `on_complete'
    from /usr/local/lib/ruby/gems/1.9.1/gems/faraday-0.8.7/lib/faraday/response.rb:9:in`block in call'
    from /usr/local/lib/ruby/gems/1.9.1/gems/faraday-0.8.7/lib/faraday/response.rb:63:in `on_complete'
    from /usr/local/lib/ruby/gems/1.9.1/gems/faraday-0.8.7/lib/faraday/response.rb:8:in`call'
    from /usr/local/lib/ruby/gems/1.9.1/gems/faraday-0.8.7/lib/faraday/request/url_encoded.rb:14:in `call'
    from /usr/local/lib/ruby/gems/1.9.1/gems/faraday-0.8.7/lib/faraday/request/multipart.rb:13:in`call'
    from /usr/local/lib/ruby/gems/1.9.1/gems/twitter-4.6.2/lib/twitter/request/multipart_with_file.rb:14:in `call'
    from /usr/local/lib/ruby/gems/1.9.1/gems/faraday-0.8.7/lib/faraday/connection.rb:247:in`run_request'
    from /usr/local/lib/ruby/gems/1.9.1/gems/faraday-0.8.7/lib/faraday/connection.rb:112:in `post'
    from /usr/local/lib/ruby/gems/1.9.1/gems/twitter-4.6.2/lib/twitter/client.rb:81:in`request'
    from /usr/local/lib/ruby/gems/1.9.1/gems/twitter-4.6.2/lib/twitter/client.rb:70:in `post'
    from /usr/local/lib/ruby/gems/1.9.1/gems/twitter-4.6.2/lib/twitter/api/utils.rb:82:in`object_from_response'
    from /usr/local/lib/ruby/gems/1.9.1/gems/twitter-4.6.2/lib/twitter/api/tweets.rb:129:in `update'
    from /usr/local/lib/ruby/gems/1.9.1/gems/twitter-4.6.2/lib/twitter.rb:52:in`method_missing'
    from (irb):25
    from /usr/local/bin/irb:12:in `<main>'

**Comment by ZeeshanAhmadKhalil** [comment]
My Clock is sync with NTP, its still giving the error
