### ISSUE TITLE
Twitter::Error::NotFound: Sorry, that page does not exist when client.follow('cnn') 

### ISSUE THREAD

**Issue by jeremyhaile** [sferik/twitter#426]
This is an authenticated client. Calling client.user, client.followers, client.update(msg), etc. works. But every time I call client.follow(any_account_name) I receive the error: Twitter::Error::NotFound: Sorry, that page does not exist

**Comment by jc00ke** [comment]
@greenmindPDX's tip on `string -> integer` was the key for me. Here's the [implementation](https://github.com/sferik/twitter/blob/d5679cfa6844d1f13bd8c404ef964cfe48b7af2b/lib/twitter/rest/utils.rb#L194-L197).

**Comment by marlabrizel** [comment]
I just solved a similar problem with hitting the `unfollow` endpoint by changing my params from string to integer.
