### ISSUE TITLE
How to send direct messages?

### ISSUE THREAD

**Issue by marianogg9** [sferik/twitter#527]
Hi there.
I'm trying to configure a ruby script to send direct messages using the Twitter rest API, and of course this great gem. I'm using:

foo.create_direct_message(user,"text")

I do know this is really wrong, but cannot find the right sintaxis for this command. Could you help me out here?
Thanks!!

**Comment by alex-thp** [comment]
Hi ! I'm trying to use you function too but I meet a problem... Here it is : 

/home/a1/.rvm/gems/ruby-2.5.1/gems/twitter-6.2.0/lib/twitter/rest/request.rb:81:in `fail_or_return_response_body': Sorry, that page does not exist. (Twitter::Error::NotFound)

And here is my code : 
client.create_direct_message(1447374817, "Salut, dis moi si ça fonctionne stp !")

1447374817 is the user ID of the target. If you know what is going wrong, I'd be glad if you'd tell me !

Thanks,
Alex
