### ISSUE TITLE
Twitter::Error: 757: unexpected token at ''

### ISSUE THREAD

**Issue by jtippett** [sferik/twitter#547]
I've recently upgraded to rails 4 and twitter 5.8.0 and am seeing strange parsing errors:

```
2.1.1 :038 > client.status "test"
Twitter::Error: 757: unexpected token at ''
  from /home/deploy/rails-apps/my_app/shared/bundle/ruby/2.1.0/gems/twitter-5.8.0/lib/twitter/rest/client.rb:96:in `rescue in request'
  from /home/deploy/rails-apps/my_app/shared/bundle/ruby/2.1.0/gems/twitter-5.8.0/lib/twitter/rest/client.rb:92:in `request'
  from /home/deploy/rails-apps/my_app/shared/bundle/ruby/2.1.0/gems/twitter-5.8.0/lib/twitter/rest/client.rb:63:in `get'
  from /home/deploy/rails-apps/my_app/shared/bundle/ruby/2.1.0/gems/twitter-5.8.0/lib/twitter/request.rb:22:in `perform'
  from /home/deploy/rails-apps/my_app/shared/bundle/ruby/2.1.0/gems/twitter-5.8.0/lib/twitter/request.rb:29:in `perform_with_object'
  from /home/deploy/rails-apps/my_app/shared/bundle/ruby/2.1.0/gems/twitter-5.8.0/lib/twitter/rest/utils.rb:39:in `perform_with_object'
  from /home/deploy/rails-apps/my_app/shared/bundle/ruby/2.1.0/gems/twitter-5.8.0/lib/twitter/rest/tweets.rb:60:in `status'
  from (irb):38
  from /home/deploy/rails-apps/my_app/shared/bundle/ruby/2.1.0/gems/railties-4.0.4/lib/rails/commands/console.rb:90:in `start'
  from /home/deploy/rails-apps/my_app/shared/bundle/ruby/2.1.0/gems/railties-4.0.4/lib/rails/commands/console.rb:9:in `start'
  from /home/deploy/rails-apps/my_app/shared/bundle/ruby/2.1.0/gems/railties-4.0.4/lib/rails/commands.rb:62:in `<top (required)>'
```

I'm not sure what could be causing this; as you can see it's a plain string with nothing weird. Is this a known issue?

**Comment by stillwyw** [comment]
Hey guys
I'm getting same error,several times, on two different machine (actually when i was using `rails 3.2.14` I wasn't having this):

    rake aborted!
    JSON::ParserError: 757: unexpected token at '{"created_at":"Mon Jan 05 23:19:00 +0000     2015","id":552242891200815104,"id_str":"552242891200815104","text":"mente aventureira, alma inquieta, ando louco por ai \u00e9 isso que me resta...","source":"\u003ca href=\"http:\/\/twitter.com\" rel=\"nofollow\"\u003eTwitter Web Client\u003c\/a\u003e","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":1125365822,"id_str":"1125365822","name":"Cain Oliveira","screen_name":"cainoliveiraa","location":"snap:cainoliveiraa","url":"http:\/\/Instagram.com\/cainoliveiraa","description":"minha mente \u00e9 uma maldade, voc\u00eas n\u00e3o sabem o quanto pesa !!","protected":false,"verified":false,"followers_count":802,"friends_count":430,"listed_count":1,"favourites_count":3970,"statuses_count":46338,"created_at":"Sun Jan 27 15:30:36 +0000 2013","utc_offset":-7200,"time_zone":"Brasilia","geo_enabled":true,"lang":"pt","contributors_enabled":false,"is_translator":false,"profile_background_color":"C0DEED","profile_background_image_url":"http:\/\/pbs.twimg.com\/profile_background_images\/550113929469255680\/j8S01MQj.jpeg","profile_background_image_url_https":"https:\/\/pbs.twimg.com\/profile_background_images\/550113929469255680\/j8S01MQj.jpeg","profile_background_tile":true,"profile_link_color":"0084B4","profile_sidebar_border_color":"FFFFFF","profile_sidebar_fill_color":"DDEEF6","profile_text_color":"333333","profile_use_background_image":true,"profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/547782445777846273\/9bQzqKar_normal.jpeg","profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/547782445777846273\/9bQzqKar_normal.jpeg","profile_banner_url":"https:\/\/pbs.twimg.com\/profile_banners\/1125365822\/1415314239","default_profile":false,"default_profile_image":false,"following":null,"follow_request_sent":null,"notifications":null},"geo":null,"coordinates":null,"place":{"id":"017453ae077eafd3","url":"https:\/\/api.twitter.com\/1.1\/geo\/id\/017453ae077eafd3.json","place_type":"city","name":"Gold Coast","full_name":"Gold Coast, Queensland","country_code":"AU","country":"Australia","bounding_box":{"type":"Polygon","coordinates":[[[153.186551712,-28.2003171475],[153.186551712,-27.708126368],[153.552171232,-27.708126368],[153.552171232,-28.2003171475]]]},"attributes":{}},"contributors":null,"retweet_count":0,"favorite_count":0,"entities":{"hashtags":[],"trends":[],"urls":[],"user_mentions":[],"symbols":[]},"favorited":false,"retweeted":false,"possibly_sensitive":false,"filter_level":"medium","lang":"pt","timestamp_ms":"1420499940096"}'

If i parse the same JSON in rails console or IRB, all worked good. Any idea?

    ruby 2.1.1
    rails 4.1.6
    twitter gem 5.13

Thanks.
