### ISSUE TITLE
Could not authenticate upload image with option possibly_sensitive

### ISSUE THREAD

**Issue by cbunhok** [sferik/twitter#577]
Hello Everybody,

I use method upload to upload image. It works fine if I do not put option possibly_sensitive. Otherwise, It returns error that "Could not authenticate you" when I put the possibly_sensitive.
Any idea?

Thanks.

**Comment by ikaiser** [comment]
hello an information,
I have a very similar problem,
I can not upload images to twitter
my code is that:

    media = @post.image.path(:original).to_s
            images = media.split('?')
            media = images[0]
            response = access_token.post(Rails.application.secrets.twitter['urls']  ['post_with_media_timeline'], feed.merge('media' => media, 'status' => @post.text_no_html), {'Content-Type' => 'multipart/form-data'})

any idea for a bug??
thanks.
