### ISSUE TITLE
Randomly getting Twitter::Error::Forbidden "Missing or invalid url parameter" for search calls

### ISSUE THREAD

**Issue by arvindr** [sferik/twitter#578]
Exception:
{"rate_limit":{"attrs":{"cache-control":"no-cache, no-store, must-revalidate, pre-check=0, post-check=0","content-length":"96","content-type":"application/json;charset=utf-8","date":"Thu, 05 Jun 2014 15:17:29 GMT","expires":"Tue, 31 Mar 1981 05:00:00 GMT","last-modified":"Thu, 05 Jun 2014 15:17:29 GMT","pragma":"no-cache","server":"tfe","set-cookie":"lang=en, guest_id=v1%3A140198144901569837; Domain=.twitter.com; Path=/; Expires=Sat, 04-Jun-2016 15:17:29 UTC","status":"403 Forbidden","strict-transport-security":"max-age=631138519","x-access-level":"read-write-directmessages","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","x-rate-limit-limit":"180","x-rate-limit-remaining":"179","x-rate-limit-reset":"1401982349","x-transaction":"7d2705dc4268fd58","x-xss-protection":"1; mode=block","connection":"close"}},"cause":"Missing or invalid url parameter.","code":195}

client = Twitter::REST::Client.new do |config|
      config.consumer_key = TwitterConfig::CLIENT_ID
      config.consumer_secret = TwitterConfig::CLIENT_SECRET
      config.access_token = twitter_handle.access_token
      config.access_token_secret = twitter_handle.access_secret
  end

query = (hello OR world ) -rt
options = {:sort_order=>:desc, :count=>15}
client.search(query, options)

We are hitting this error intermittently. Whats more weird is that a search query which was successful before starts failing randomly.
Once we hit this error, all our search API calls start failing. After ~20 - 30 minutes(sometimes more) it starts working again.

**Comment by rinkrat248** [comment]
I realize this is really old, but I'm also receiving the same error intermittently (usually when iterating over a large search result), and I was wondering what the issue with your code was and how you fixed it?

**Comment by adrielegf** [comment]
> I realize this is really old, but I'm also receiving the same error intermittently (usually when iterating over a large search result), and I was wondering what the issue with your code was and how you fixed it?

@rinkrat248 I'm 2 years late. My app was also throwing this error, randomly, and I fixed it by requesting the tweets in batches. It looks like the twitter api throws this error when we try to get a big amount of data - but it's not clear how much is too much. So my way out was to retrieve tweets in groups.
