### ISSUE TITLE
Only 10 (or less) results using search

### ISSUE THREAD

**Issue by simo2409** [sferik/twitter#636]
Hello,
ruby -v

```
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin14.0.0]
```

twitter gem version: 5.13.0

Doing

```
client.search("#seratina").attrs[:statuses].size
```

I get 10 results, so I tried with

```
client.search("#seratina", :count => 50).attrs[:statuses].size
```

and I get still 10 results, but if I try this

```
client.search("#seratina", :count => 3).attrs[:statuses].size
```

I get (correctly) 3

Reading https://dev.twitter.com/rest/reference/get/search/tweets I see that default 'count' is 15 and reading gem's code I see the max is 100, so why I'm not able to get more than 10 results? Am I missing something?

Thank you very much

**Comment by tedma4** [comment]
I'm getting the same problem, but it seems to only happen with result_type: "popular"
I tried it with a couple different searches and got the exact same thing.

irb(main):009:0> posts = client.search("#football", result_type: "popular").to_a.length
=> 15

irb(main):010:0> posts = client.search("#science", result_type: "popular").to_a.length
=> 15

irb(main):011:0> posts = client.search("#ruby", result_type: "popular").to_a.length
=> 6

irb(main):012:0> posts = client.search("#football").take(20).to_a.length
=> 20

irb(main):013:0> posts = client.search("#science").take(20).to_a.length
=> 20

irb(main):014:0> posts = client.search("#ruby").take(200).to_a.length
=> 200

Is there a way to get more results from result_type: "popular" ?
