### ISSUE TITLE
Unable to post multiple images using update_with_media

### ISSUE THREAD

**Issue by nicholasjon** [sferik/twitter#638]
I can use update_with_media to post single images without a problem, but whenever I attempt to post _multiple_ images via update_with_media, I get the following error: 

```
Twitter::Error::UnacceptableIO: The IO object for media must respond to to_io
```

I'm trying to follow the example from: https://github.com/sferik/twitter/blob/master/examples/Update.md

```
media = %w(/path/to/media1.png /path/to/media2.png).map { |filename| File.new(filename) }
client.update_with_media("I'm tweeting with @gem!", media)
```

Here's how I'm setting up my client: 

```
client = Twitter::REST::Client.new do |config|
  config.consumer_key        = CONSUMER_KEY
  config.consumer_secret     = CONSUPER_SECRET
  config.access_token        = user.twitter_token
  config.access_token_secret = user.twitter_secret
end
```

The array of media I have looks like: 

```
media
 => [#<File:/path_to_file/photo/9aN9KzkLQa/9aN9KzkLQa-full.jpg>, #<File:/path_to_file/photo/EUcjNHr5jB/EUcjNHr5jB-full.jpg>]
```

And here's how I'm trying to make my post: 

```
client.update_with_media("tweet text",media)
```

Some more info: 

The following work: 

```
client.update_with_media("tweet text",media.first) # successful
client.update_with_media("tweet text",media.last) # successful
```

This does not: 

```
client.update_with_media("tweet text",[media.first])
```

**Comment by Roach** [comment]
You'll want to upload the media first, then reference the media IDs when posting the Tweet:

```
media_ids = %w(/path/to/media1.png /path/to/media2.png).map do |filename| 
 client.upload File.new filename
end

tweet = client.update "tweet text", {media_ids: media_ids.join(',')}
```

**Comment by tomoyuki28jp** [comment]
@Roach Your comment helps me out, thanks! :)

**Comment by jrgillick** [comment]
This works for me with images. Has anyone had success uploading video? When I run this code:

client.upload(file)

I get this error:

Faraday::TimeoutError: Net::ReadTimeout

**Comment by sagarpreet-chadha** [comment]
@nicholasjon , @jrgillick , @Roach , can any of you help me with the following problem . 

I was trying to use `client.update_with_media("I'm tweeting with @gem!", File.new("/path/to/media.png"))` , but could not understand how to make `File object` for argument .

In short , i want to **tweet this image** [https://pbs.twimg.com/profile_images/793855561456418816/7ysHNRUu.jpg](https://pbs.twimg.com/profile_images/793855561456418816/7ysHNRUu.jpg) , with **message "Hi"** , but couldn't figure out the arguments here . 

Thank you in advance 😄 !

**Comment by andypiper** [comment]
update_with_media was deprecated by Twitter about 3 years ago. You’d be better off following the example @roach posted above with the two-stage upload and then update method.

**Comment by sagarpreet-chadha** [comment]
Thank you @andypiper for your reply ! 

**Still i am not able to upload image** , i tried following : 

`media_ids = %w(https://pbs.twimg.com/profile_images/793855561456418816/7ysHNRUu.jpg).map do |filename| 
	 		 client.upload File.new filename
		end`

and then : 
`tweet = client.update "tweet text", {media_ids: media_ids.join(',')}`

ERROR IS :  
<img width="1270" alt="screen shot 2018-01-28 at 12 44 52 am" src="https://user-images.githubusercontent.com/14952645/35475446-912a200e-03c4-11e8-9eac-aacec118e381.png">

**Comment by sagarpreet-chadha** [comment]
And tried this to : 

`media_ids = %w(https://a.tiles.mapbox.com/v3/jywarren.map-lmrwb2em/0/0/0.png).map do |filename|`
			`require 'open-uri'`
			`open('image.png', 'wb') do |file|`
	 		` file << open(filename.to_s).read`
	 		 `client.upload File.new file`
			`end`
		`end`

and then : 

`tweet = client.update "tweet text", {media_ids: media_ids.join(',')}`

shows ERROR : 

<img width="1010" alt="screen shot 2018-01-28 at 12 50 05 am" src="https://user-images.githubusercontent.com/14952645/35475480-39218900-03c5-11e8-8f2e-feaf1e4195ad.png">

**Comment by andypiper** [comment]
You cannot provide a URL as a media ID. You have to upload the image to the media/upload endpoint, and use the ID returned from there.
