### ISSUE TITLE
Support for HTTPS proxy 

### ISSUE THREAD

**Issue by clever-trevor** [sferik/twitter#639]
Hi, 
I'm trying to get 5.12.0 (also tries 5.13.0) GEM working through a Proxy server but it looks like this functionality was removed.

I've tried various things but it looks like the connection.rb module is opening a socket to Twitter and I can't see any code which looks like it is referencing a proxy.

Possibly, I'm doing something wrong so either is there an example of how to use a proxy server, or are there any plans to add this back in ?

**Comment by untergeek** [comment]
I'm curious about this as well.

**Comment by stve** [comment]
@schmorgs @untergeek can you guys offer some pointers on a simple proxy I can run locally to test with? by the looks of things, this should be pretty easy to support but I don't use a proxy myself. Thanks

**Comment by untergeek** [comment]
Sure.  What's your dev platform?  On Linux it's pretty straightforward to install Squid Proxy (which is what I was testing with).  If you're using a Mac, it's a little bit more work to get brew installed, but then it's just `brew install squid` (or something rather like that).  If you're on windows, that's a bit trickier.

**Comment by untergeek** [comment]
On Ubuntu (or probably any Debian style): `sudo apt-get install squid`.  The configuration options needed for change are minimal (especially if running on localhost).

**Comment by stve** [comment]
Thanks @untergeek. I was able to get squid installed on my mac. I'm hoping this is pretty easy to accomplish, i'll let you know.

**Comment by untergeek** [comment]
Fantastic!  Thanks!

**Comment by untergeek** [comment]
I'm happy to help test a branch when you get one, btw.

**Comment by stve** [comment]
ok, so i'm a noob when it comes to proxies. I have a default squid install from homebrew, it's using the out of the box config: https://gist.github.com/stve/f5ad60cccf701f213116

When attempting to route requests through the proxy, I get `X-Squid-Error: ERR_DNS_FAIL 0"` any thoughts as to what I need to change to make this work?

**Comment by untergeek** [comment]
Sorry for not responding sooner, I was tied up yesterday.

You may need to manually specify some settings in the `/usr/local/etc/squid.conf` file.  One that makes sense for OS X (due to dual ipv4 and ipv6 stacks) is

```
dns_v4_first on
```

You may also need to manually specify your dns servers:

```
dns_nameservers 10.0.0.1 192.172.0.4
```

Substitute your own ips here.

When you've changed,  you can make squid re-read the config with:

```
squid -k reconfigure
```

**Comment by stve** [comment]
@untergeek Thanks for the squid suggestions - that did the trick. If you point to the [`proxy-support`](https://github.com/sferik/twitter/tree/proxy-support) branch you'll be able to verify that it's working. I've had success testing locally. If you are able to, it'd be great if you could test REST and Streaming implementations.

Configuration is like so:

```ruby
client = Twitter::Streaming::Client.new do |config|
  config.consumer_key        = 'CK'
  config.consumer_secret     = 'CS'
  config.access_token        = 'AT'
  config.access_token_secret = 'AS'
  config.proxy               = {host: '127.0.0.1', port: 3128, username: 'foo', password: 'bar'}
end
```

`username` and `password` are obviously optional. Thanks!

**Comment by untergeek** [comment]
WOOHOO!  I'm going to test this branch now.  Thanks!

**Comment by sferik** [comment]
@untergeek How’s the testing going? Did this work for you?

**Comment by untergeek** [comment]
Sorry!  I got stymied by some other work items.  I hope to test this over the weekend, or Monday at the latest.

**Comment by sferik** [comment]
@untergeek Ping. Any update?

**Comment by untergeek** [comment]
I am so sorry.  I work for Elastic (formerly Elasticsearch) on the Logstash project.  We're in the middle of an all-hands meeting after our first conference, Elastic{ON}, last week.  I have had no time with all of these machinations.  It is very important that I get this tested and done, but it's been back-burnered until Tuesday at the earliest.

**Comment by untergeek** [comment]
Sorry to keep you waiting so long!  Thanks for your patience.

I'm still not able to connect, but that might be a misconfiguration on my end.  Let me show you what I have.

### Client building:
```
    # proxyobj should follow the pattern:
    # http[s]://[user:pass@]host.tld[:port]
    http_method = @proxy_secure ? 'https' : 'http'

    if @proxy_user && @proxy_pass
      proxyauth = @proxy_user + ':' + @proxy_pass.value + '@'
    else
      proxyauth = ""
    end

    if @proxy_host && @proxy_port
      proxyobj = http_method + '://' + proxyauth + @proxy_host + ':' + @proxy_port.to_s
    elsif @proxy_host
      # Not a common occurrence, I should think, to have a proxy on port 80
      # but we'll catch it anyway
      proxyobj = http_method + '://' + proxyauth + @proxy_host
    else
      # Ensure a nil value here
      proxyobj = nil
    end

    @client = Twitter::Streaming::Client.new do |c|
      c.consumer_key = @consumer_key
      c.consumer_secret = @consumer_secret.value
      c.access_token = @oauth_token
      c.access_token_secret = @oauth_token_secret.value
      if proxyobj
        @logger.debug? && @logger.debug("Using proxy", :proxy => proxyobj.to_s)
        c.proxy = proxyobj
      end
    end
```

The output of that `@logger.debug` line is:

```
Using proxy {:proxy=>"http://192.168.123.204:3128", :level=>:debug}
```

And the associated message I'm getting indicates a [failure at line 113](https://github.com/sferik/twitter/blob/proxy-support/lib/twitter/streaming/client.rb#L113)

```
Connection refused - Connection refused {:exception=>#<Errno::ECONNREFUSED: Connection refused - Connection refused>, :backtrace=>["org/jruby/ext/socket/RubyTCPSocket.java:126:in `initialize'", "org/jruby/RubyIO.java:851:in `new'", ".../bundle/jruby/1.9/gems/twitter-6.0.0/lib/twitter/streaming/connection.rb:17:in `stream'", ".../bundle/jruby/1.9/gems/twitter-6.0.0/lib/twitter/streaming/client.rb:119:in `request'",
```

I used ellipsis to shorten the path to the gem.

As a matter of guarantee, I use a firewall--local to my laptop--to prevent outbound to twitter IPs.  I do this to ensure connections aren't sneaking around and bypassing the proxy.

**Comment by untergeek** [comment]
I should also not there are no apparent attempted connections to the proxy, as indicated by the absence of log lines.

**Comment by stve** [comment]
@untergeek thanks for testing this out, it looks like you are passing the proxy through as a string, whereas [`http.rb's implementation`](https://github.com/httprb/http.rb#proxy-support) accepts the host and port as parameters. Right now, the code is only equipped to handle a proxy defined via a hash:

```ruby
proxy = {
  host: '127.0.0.1',
  port: 3328,
  username: 'proxy_username', # optional
  password: 'proxy_password', #optional
}

client = Twitter::REST::Client.new do |config|
  config.consumer_key        = "YOUR_CONSUMER_KEY"
  config.consumer_secret     = "YOUR_CONSUMER_SECRET"
  config.access_token        = "YOUR_ACCESS_TOKEN"
  config.access_token_secret = "YOUR_ACCESS_SECRET"
  config.proxy               = proxy
end
```

If you try using a hash do you still encounter issues?

But your code makes me wonder how `HTTP` could support both http and https protocols when neither is specified by the options it exposes.  I suppose we could also accept the proxy as a string and decompose it into the parameters that get passed to `HTTP.via` as well, what's the most typical way by which these are configured? Pointers to other ruby implementations appreciated :smile_cat:

**Comment by untergeek** [comment]
I'll try this in the morning.  Passing as a hash is just fine.  I just saw some examples of proxy with net/http that used the string and didn't realize you were using http.rb

I asked on the http.rb repository if it supports SSL proxies.  I will wait for a response from them.

**Comment by untergeek** [comment]
Hmmm... I read through the source here: https://github.com/httprb/http.rb/blob/master/lib/http/request.rb#L111-L130

So I built my proxy has this way:

```
    if @proxy_host
      proxyobj[:proxy_address] = @proxy_host
      proxyobj[:proxy_port] = @proxy_port
      if @proxy_user
        proxyobj[:proxy_username] = @proxy_user
      end
      if @proxy_pass
        proxyobj[:proxy_password] = @proxy_pass
      end
```

With the resulting object (debug logging):

```
Using proxy {:proxy=>"{:proxy_address=>\"192.168.123.204\", :proxy_port=>3128}"
```

I'm still getting the same connection error as before.

**Comment by stve** [comment]
hi @untergeek, `HTTP::Request` is a lower-level object than what the [public API exposes](https://github.com/httprb/http.rb/blob/master/lib/http/chainable.rb#L112-L128), which is why i opted to accept the proxy as a hash and [pass it's values directly to `HTTP.via`](https://github.com/sferik/twitter/blob/a5fa3fcea5e49abfd77a5a8b73fc1bfd471a8af5/lib/twitter/rest/request.rb#L108-L118). Your comment above makes me wonder if your usage is different than my example.  I'd expect it to look something like this:

```ruby
proxy = {}

if @proxy_host && @proxy_port
  proxy.merge!(host: @proxy_host port: @proxy_port)
  
  if @proxy_user && @proxy_pass
    proxy.merge!(username: @proxy_user, password: @proxy_pass.value)
  end
end

@client = Twitter::Streaming::Client.new do |c|
  c.consumer_key = @consumer_key
  c.consumer_secret = @consumer_secret.value
  c.access_token = @oauth_token
  c.access_token_secret = @oauth_token_secret.value
  if !proxy.empty?
    @logger.debug? && @logger.debug("Using proxy", :proxy => proxy)
    c.proxy = proxy
  end
end
```
