### ISSUE TITLE
Not getting full details of tweet.

### ISSUE THREAD

**Issue by asharmaror123** [sferik/twitter#643]
client = Twitter::REST::Client.new do |config|
        config.consumer_key = consumer_key
        config.consumer_secret = consumer_secret
        config.access_token = access_token
        config.access_token_secret = access_token_secret
      end

     response = client.user_timeline("powerwod")
    [#<Twitter::Tweet id=553454087769825280>, #<Twitter::Tweet id=553451939245981697>,   #<Twitter::Tweet id=553384104885243906>, #<Twitter::Tweet id=553383344072056834>, ] 

We are getting only tweet id instead of full details of tweet.

Is there any way to get tweet details ?

**Comment by sferik** [comment]
You’re just looking at the truncated string representation of a tweet, as defined by the `#inspect` method. You can define `inspect` on an object to be any string. For example:

```ruby
irb(main):001:0> smile = Object.new
=> #<Object:0x007fe402829bf8>
irb(main):002:0> def smile.inspect() ":)" end
=> :inspect
irb(main):003:0> smile
=> :)
```

The data is all in there, you just need to use methods to get it out. For a list of available methods you can review the [documentation](http://www.rubydoc.info/gems/twitter/Twitter/Tweet) or simply call the `methods` method on any `Twitter::Tweet` object.
