### ISSUE TITLE
Add Twitter Status With Image

### ISSUE THREAD

**Issue by ikaiser** [sferik/twitter#646]
Hy everyone,
i have an isseu, sorry if I could not use it with precious gem, but I found the code already set, and now I have a problem. I have to create a post on Twitter using the REST API, this isresponsible my code:

    api = Rails.application.secrets.twitter['api']
    secret = Rails.application.secrets.twitter['secret']
    api_url = Rails.application.secrets.twitter['urls']['api']

    consumer = OAuth::Consumer.new(api, secret,
                                   { :site => api_url,
                                     :scheme => :header
                                   })
    u_token  = aut_tw.token
    u_secret = aut_tw.secret
    access_token = Authentication.twitter_prepare_access_token(consumer, u_token, u_secret)

    media = @post.image.path(:original).to_s
    images = media.split('?')
    media = images[0]

    response = access_token.post('https://upload.twitter.com/1.1/media/upload.json', feed.merge('media' => media, 'status' => @post.text_no_html), {'Content-Type' => 'multipart/form-data'})

but I always get errors from twitter.

someone can help me?
thanks.

**Comment by 8bithero** [comment]
I guess my reply is a bit late, but what errors are you getting?

**Comment by stve** [comment]
@ikaiser presumably you've found a solution. Since this isn't really applicable to this library, I'm going to close this out. Thanks.
