### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by apiology** [sferik/twitter#647]
Hi!

Thanks for bumping your 'http' dependency, which helped it match similar bumps in other gems used by my app.

Would it be possible for you to push a new release now that dependencies are updated?

Thanks!
Vince

**Comment by sferik** [comment]
Hi Vince,

The current `master` branch includes backward-incompatible changes, so I can’t release it without bumping the major version number. If you look at the [v6 milestone](https://github.com/sferik/twitter/milestones/v6), it contains two open issues blocking the release: https://github.com/sferik/twitter/issues/535 and https://github.com/sferik/twitter/issues/565, both of which are related to streaming and assigned to @stve. As soon as those issues are resolved, we can release version 6.0.0.

Alternatively, I can checkout the `v5.13.0` tag as a branch, cherry-pick the relevant patches, and release another version in the 5.x series.

@stve: Any thoughts on when those two issues might be resolved?

Erik

**Comment by stve** [comment]
@sferik i got bogged down over the holidays but will have a bit more free time to focus on this now. hopefully soon.

**Comment by sferik** [comment]
@stve Great! Then I think I’ll wait until your done to make a new release.

@apiology In the mean time, if you want to run the latest code in your project, you can update your `Gemfile` to look like this:

```ruby
gem 'twitter', git: 'https://github.com/sferik/twitter.git', branch: 'master'
```

However, the `master` branch may be unstable and is unsuitable for most production environments.

**Comment by apiology** [comment]
Will do--thanks!
