### ISSUE TITLE
Pull DM image from media_url

### ISSUE THREAD

**Issue by juniorjp** [sferik/twitter#648]
Hi,

I am trying to download to my server a image from a DM. I have the client access_token and access_token_secret and the url, like that:
   https://ton.twitter.com/i/ton/data/dm/557585298255667200/557585298276642817/vbmbqcoC.png

But since the URL is not public, I need to send a oauth request to that URL. Is it possible with this gem?

Edit:
I tried
```
   client.get(image_url)
```

but it returns 302.

**Comment by stve** [comment]
@juniorjp the TON API only exposes means by which to upload images, I don't see any way to authenticate against `ton.twitter.com` to retrieve assets, it appears this is not currently possible.

**Comment by AgoraSecurity** [comment]
Any updates on this?
