### ISSUE TITLE
Missing status responses for Twitter::Streaming::Client

### ISSUE THREAD

**Issue by mroth** [sferik/twitter#649]
There are a number of status messages that can be sent back from the Streaming API in addition to normal tweets/events, as defined by https://dev.twitter.com/streaming/overview/messages-types.

Currently it appears the only two supported are `Twitter::Streaming::DeletedTweet` and `Twitter::Streaming::StallWarning`.

Implementing all of these messages would be great, and some of them are quite important -- for example, LIMIT notices (different from stall warnings), or DISCONNECT messages that contain a reason.

**Comment by stve** [comment]
hi @mroth I've added this to the list of streaming updates planned for version 6 of the gem, you can track these changes on #631 thanks!
