### ISSUE TITLE
uninitialized constant Twitter::Media::AnimatedGif

### ISSUE THREAD

**Issue by nidev** [sferik/twitter#653]
Using gem version 5.13.0, I experienced NameError while userstreaming.

Exception was 'NamerError' and It said Twitter::Media::AnimatedGif had not been initialized before and I found there's no 'AnimatedGif' under Twitter::Media.

This exception is raised when a tweet including animated GIF image appears on Twitter timeline.

I attach a Gist link, which contains stack trace : https://gist.github.com/nidev/2657e3deab36a94c80e5

**Comment by nidev** [comment]
I made a simple Ruby class inheriting Twitter::Media::Photo and It gives me no exception but a GIF thumbnail image in PNG format.

Below patch is what I did for this problem. Is it reasonable?

```diff
--- photo.rb.orig	2015-02-04 11:53:32.458362194 +0900
+++ photo.rb	2015-02-04 11:53:52.327226961 +0900
@@ -19,5 +19,8 @@
       end
       memoize :sizes
     end
+
+    class AnimatedGif < Photo
+    end
   end
 end
```

**Comment by stve** [comment]
@nidev Thanks for finding this. Could you post the URL to the tweet so we can take a look at the response? 

It's reasonable to assume that there's minimal differences between a photo and an animated gif but I'd like to verify that's the case.

**Comment by nidev** [comment]
@stve I really appreciate your comment.

URL to the tweet: https://twitter.com/jindol0501/status/562805030382993408
(The tweet says like 'GIF file made by himself is not smooth (disappointed)' in Korea, just let you know.)

Though my Ruby application got NameError from other tweet (and it couldn't record tweet_id and username), I used that for reproducing the problem.

**Comment by stve** [comment]
@nidev interesting. I'm not seeing any media attributes in the tweet coming through the API right now.  Here's the response I get: https://gist.github.com/stve/aa76630286eb5b4a8615

Twitter [recently announced animated gif support](https://twittercommunity.com/t/adding-animated-gifs-via-rest-and-streaming-apis/30070) so this is probably related.

**Comment by stve** [comment]
Ah! Looking at your gist again, I see that you were using the streaming API, I guess that explains why it's not in the REST API right now - there's some variance between the two endpoints.

**Comment by nidev** [comment]
@stve Sorry for forgetting to mention it was happened during user streaming. Just, it was my mind to be written but forgot accidentally.

I got a gist here to show JSON data under user streaming. The tweet with this gist also has GIF animation image: https://gist.github.com/nidev/91b2ee680b54d29ff0e7

I found very interesting section (from line number 263):
```json
 "extended_entities": {
"media": [
{
"id": 521757602405822464,
"id_str": "521757602405822464",
"indices": [
28,
50
],
"media_url": "http://pbs.twimg.com/tweet_video_thumb/Bz2nxmZCMAAPPee.png",
"media_url_https": "https://pbs.twimg.com/tweet_video_thumb/Bz2nxmZCMAAPPee.png",
"url": "http://t.co/tRrBKRwPWU",
"display_url": "pic.twitter.com/tRrBKRwPWU",
"expanded_url": "http://twitter.com/lNVENTlONS/status/521757623775801344/photo/1",
"type": "animated_gif",
"sizes": {
"thumb": { 
```

"type": "animated_gif" is very new to me. Never seen on REST.

**Comment by stve** [comment]
@nidev This is perfect, I'm glad you had a copy of the JSON. I'll take a look through to see what is needed on our end to support it. Thanks!

**Comment by jronallo** [comment]
I'm getting this error now too. I think this has to do with them getting ready to include videos (for both animated GIFs converted to video and the new videos) in both the streaming and REST APIs. 

Also note that I've begun to sporadically see animated GIFs in Tweetdeck so it seems they're testing some things with the API endpoints.

This announcement might help too:
https://twittercommunity.com/t/adding-animated-gifs-via-rest-and-streaming-apis/30070

**Comment by sferik** [comment]
Thanks for the issue report. The `master` branch is currently targeting [v6](https://github.com/sferik/twitter/milestones/v6), which is not yet ready to release, so any pull requests should be based on the [`5-stable`](https://github.com/sferik/twitter/tree/5-stable) branch. Once that patch is applied, I’ll release version 5.14.0, as I expect this issue to increase in frequency as Twitter continues to roll out this feature.

**Comment by goddamnyouryan** [comment]
I'm seeing this error for both AnimatedGifts and I am getting the error `uninitialized constant Twitter::Media::Video` as well.

**Comment by nidev** [comment]
As @goddamnyouryan commnented, I suffered same issue just right before. I think media/video.rb and media/video_info.rb in (/lib/twitter/media)[https://github.com/sferik/twitter/tree/master/lib/twitter/media] master branch may need be backported to 5-stable branch.

However current issue is focusing on Twitter::Media::AnimatedGif (at that time, I could see only that). Do we have to open a new issue to deal with new features in Twitter user streaming?

**Comment by jose8a** [comment]
I'm also running into this issue and only using the REST API.  I just noticed it earlier today, but apparently it first occurred in my app as early as 2 days ago.

**Comment by Arsenalist** [comment]
Getting the "uninitialized constant Twitter::Media::AnimatedGif" error:

Example tweet:

https://twitter.com/CBSSports/status/564998590347874307

I'm using the REST API, not streaming.

**Comment by nidev** [comment]
Pull request #655 is merged.

**Comment by sferik** [comment]
:ship: https://rubygems.org/gems/twitter/versions/5.14.0
