### ISSUE TITLE
Adding metadata to a tweet

### ISSUE THREAD

**Issue by nimkar** [sferik/twitter#654]
Is it possible to add metadata to a tweet ? So that when a tweet is converted to hash with to_h or json to be stored in database the metadata is also stored along with the tweet without having to store the metadata separately ?

**Comment by stve** [comment]
assuming you have a `Twitter::Tweet` object, you can access the response as a hash using `#to_h`. If you are looking to store this data, I'd recommend merging your metadata into this when you persist. Something like this

```
db.save(tweet.to_h.merge(metadata: {}))
```
