### ISSUE TITLE
update method is misleading

### ISSUE THREAD

**Issue by Intrepidd** [sferik/twitter#656]
Hi,

We had a tough issue with twitter as we found some very inconsistent behavior regarding the tweets we store.

The fact that the ``update`` method will return the last tweet sent if it is a duplicate was not expected and caused some really hard to debug errors.

Wouldn't it be better if the ``update`` method returned nil instead of the last sent tweet ?

Cheers

**Comment by jarthod** [comment]
Indeed this is very error prone as you can't know if it's your tweet or not.
If it doesn't raise it should just return nil.

**Comment by stve** [comment]
The method you'll want to use instead is [`Twitter::REST::Tweets#update!`](http://www.rubydoc.info/gems/twitter/Twitter/REST/Tweets:update!) which will raise a `Twitter::Error::DuplicateStatus` on duplicates whereas `update` works as you've described above.

**Comment by stve** [comment]
I agree, that the documentation on `update` could be clearer and will make sure we adjust our documentation in the next release.

**Comment by jarthod** [comment]
Yes, we saw it and we'll use the `update!` method for sure, we don't understand why the `update` method even exist like this :) We just want to avoid other users loosing as much time as we did on this issue. We ended up having duplicated id in our DB with post that didn't even exists on twitter, causing all kind of threading issues. We never suspected the gem could do something like this, doing another API call to return a plain correct response with a totally different tweet when the server is actually returning an error is kind of crazy.

And by the way, if this was implemented thinking "_if it's a duplicate error it'll be the same tweet anyway_", this is plain wrong. If you post A, then B, then A, twitter will return an error and you'll return B. So the return value of `update` is actually meaningless and dangerous.

**Comment by stve** [comment]
It's not apparent from the commit where it was introduced (02b6cb31ccf1fcea3452bb84aa2113d00809eec3) but if I ventured to guess, it was to support a graceful fallback.

@sferik what are your thoughts around deprecating `update` in favor of `update!` in `6.x`? I think I'd be in favor of always having it raise an error in this scenario.

**Comment by jarthod** [comment]
It seems there's even a spec for this:
```ruby
  it 'returns a Tweet' do
    tweet = @client.update("The problem with your code is that it's doing exactly what you told it to do.")
    expect(tweet).to be_a Twitter::Tweet
    expect(tweet.text).to eq('Happy Birthday @imdane. Watch out for those @rally pranksters!')
  end
```
So this was probably done on purpose ? In this case I would like to know why ;)

Otherwise to me it's fine to have two version, one which raises and one silent, but the silent should definitely not return the last tweet (moreover this is another API call, which can fail too...), It should simply return nil.

**Comment by Intrepidd** [comment]
Yes, 2 versions are fine but the problem lies in the behavior of ``update``, it's unexpected and not even documented, therefore error prone. I can't see the use case of returning the last tweet, you want to know when your tweet is not published.

**Comment by sferik** [comment]
I’m open to reconsidering the default behavior in version 6.

**Comment by Intrepidd** [comment]
Also, while we're there, I noticed there is an inconsistency with the ``create_direct_message`` method, this one will raise ``Twitter::Error::Forbidden: There was an error sending your message: Whoops! You already said that.`` if a private message is a duplicate, shouldn't we also raise an ``Twitter::Error::DuplicateStatus`` instead ?

**Comment by Intrepidd** [comment]
It's probably because twitter answers "Status is a duplicate" for public tweets and "Whoops, you already said that" for private messages.

Would you like a pull request that adds this case to error.rb and some specs ?
