### ISSUE TITLE
Expose RateLimit for all requets

### ISSUE THREAD

**Issue by MaxSchmeling** [sferik/twitter#658]
The Twitter API returns rate limit information for all endpoints as far as I can tell. I would like to be able to access this information from any request.

I'm planning to submit a pull request for this feature. I wanted to log this issue to get any thoughts on implementation before pushing forward.

My first thought is to add a `Response` object that has a `rate_limit` accessor and a `response_data` accessor or something along those lines. 

If I come up with a better approach, I'll post here.

**Comment by stve** [comment]
hi @MaxSchmeling, there's been some progress on this recently, you'll want to review #635 for more details. If you search for rate limit on this repository, you'll see that this is oft discussed topic but we haven't included support for it for a variety of reasons.

**Comment by MaxSchmeling** [comment]
@stve from what I'm reading (and I very well could be missing something), the main issue is thread safety and synchronization. I don't really want the twitter gem to try to keep an up to date value for rate limiting. I simply need it to expose the headers that come back with every response. In my use case, the API calls will be made in background workers that could be happening in multiple processes across multiple hosts. The gem definitely can't synchronize that.

Maybe what I'm wanting is really a different concept from what the RateLimit is trying to be?

Thoughts?

**Comment by sferik** [comment]
@MaxSchmeling I’d specifically direct you to the discussion in https://github.com/sferik/twitter/issues/318#issuecomment-9273939. My opinion hasn’t wavered much in the 2+ years since then. I’m not convinced there’s a good way to preempt 429 responses before they occur. That said, I’m open to a comprehensive, thread-safe proposal. Please reopen this issue if you’ve developed one.
