### ISSUE TITLE
Support for proxy with streaming?

### ISSUE THREAD

**Issue by untergeek** [sferik/twitter#659]
I have poked around the code all day, even going so far as to hack in some things manually in testing.

I cannot seem to get streaming to support the use of proxies, even with the proxy properly passed through:

```
  @client = Twitter::Streaming::Client.new do |c|
      c.consumer_key = @consumer_key
      c.consumer_secret = @consumer_secret.value
      c.access_token = @oauth_token
      c.access_token_secret = @oauth_token_secret.value
      c.proxy = "http://192.168.123.204:3128"
  end
```

I've dumped the contents of `@client.proxy` and can confirm that the expected object is contained.

I've also forced the proxy issue by blocking outbound traffic to the subnet used by api.twitter.com so that all traffic there must go through the proxy.

I get this error:
```
Connection refused - Connection refused {:exception=>#<Errno::ECONNREFUSED: Connection refused - Connection refused>
```

Can you please explain why this is not functioning?

**Comment by untergeek** [comment]
I should add that connectivity to the proxy is verified, and it is a different host from the one on which I am testing.

**Comment by stve** [comment]
@untergeek let's discuss in #639
