### ISSUE TITLE
Iterating all followers

### ISSUE THREAD

**Issue by alexhanh** [sferik/twitter#661]
Hey and thank you for this excellent gem. I'm trying to get user's all followers with the following code:

``` ruby
def all_followers(screen_name)
  client = Twitter::REST::Client.new do |config|
    config.consumer_key        = "..."
    config.consumer_secret     = "..."
    config.access_token        = "..."
    config.access_token_secret = "..."
  end

  cursor = nil
  begin
    cursor = client.followers(screen_name, { :count => 200 })
  rescue Twitter::Error::TooManyRequests => error
    puts "#{Time.current} Rate limited, sleeping for #{error.rate_limit.reset_in}"
    sleep error.rate_limit.reset_in + 1
    retry
  end

  begin
    cursor.each do |follower|
      total_followers += 1
      user = User.where(twitter_id: follower.id).first

      if user
        # existing user
      else
        User.create!(twitter_id: follower.id)
      end
    end
  rescue Twitter::Error::TooManyRequests => error
    puts "#{Time.current} Rate limited, sleeping for #{error.rate_limit.reset_in}"
    sleep error.rate_limit.reset_in + 1
    retry
  end

  puts "Added #{total_followers}"
end
```

Unfortunately, the number of followers reported by Twitter for the user and how many end up being in the database don't match up. It's worth mentioning that the TooManyRequests is triggered multiple times. I wonder if this is causing the cursor to somehow reset or some other weirdness happening?

**Comment by andreykul** [comment]
I'm not sure what version you are using, but it as simple as 

    client = Twitter::REST::Client.new do |config|
     config.consumer_key        = "..."
     config.consumer_secret     = "..."
     config.access_token        = "..."
     config.access_token_secret = "..."
    end

    all_followers = client.followers

You are done, it will grab all the followers without any additional iteration or anything.
Give it a try and let me know if it worked fine.

**Comment by alexhanh** [comment]
Hi @andreykul 

I'm on the version 5.14.0.

As I'm reading through the source, `client.followers` will ultimately call https://github.com/sferik/twitter/blob/master/lib/twitter/rest/utils.rb#L107 and create a new cursor object, but I don't see it fetching the full collection with the cursor.

Also, I don't see where the `Twitter::Error::TooManyRequests` is handled internally (if it would indeed fetch the whole collection).

**Comment by timsly** [comment]
I added experimental fix(#712) that should theoretically fix your problem

**Comment by subimage** [comment]
Posted this on a pull request, but seems more relevant here.

Why isn't followers/following getting friend_ids, then bulk loading using https://dev.twitter.com/rest/reference/get/users/lookup ? It makes the gem unnecessarily slow from what I can see.

This is what I believe I have to do in order to prevent senseless API hits and rate limiting.

```ruby
# When authorized from Twitter, grab followed users
def twitter_followed_users
  @twitter_followed_users ||= begin
    client = self.twitter_client
    
    # Returns pages of 5k
    friend_ids = begin
      client.friend_ids.to_a
    rescue Twitter::Error::TooManyRequests => e
      sleepy_time = e.rate_limit.reset_in + 1
      Rails.logger.debug("friend_ids - sleeping #{sleepy_time}")
      retry
    end

    # Returns pages of 100 - better than 20 at a time with friends/list
    following = begin
      client.users(friend_ids).to_a
    rescue Twitter::Error::TooManyRequests => e
      sleepy_time = e.rate_limit.reset_in + 1
      Rails.logger.debug("following - sleeping #{sleepy_time}")
      sleep sleepy_time
      retry
    end

    following
  end
end
```

Am I missing something?

**Comment by yb66** [comment]
Is anything happening with this? I'm having this problem, I get 320 users before rate limit hits, and the next call hits the same 320.

An iterator would be nice, then I could control it if I wanted. Is there a problem with the pull request in #712 or not? That thread seems to have died out.

Is there a way to call https://dev.twitter.com/rest/reference/get/users/lookup directly? I haven't found something like that in the docs yet.

Any help, much appreciated.

Regards,
iain

**Comment by yb66** [comment]
Further to this, I agree with https://github.com/sferik/twitter/pull/626#issuecomment-61698289, in that I'd prefer to not hit the rate limit and have more control. The example on rate limiting doesn't help with that.

Regards,
iain
