### ISSUE TITLE
User streaming just waits infinitely when connection becomes stalled 

### ISSUE THREAD

**Issue by nidev** [sferik/twitter#664]
I use 5.14.0 version  of twitter gem and I've been doing some tests on my application. The purpose of the test is to make sure that my application tries to reinitiate user streaming, when any TCP/IP level problem occurs.

I ran user streaming and restarted my router after a minute. I saw user streaming stopped at the time when the router was restarted. There was no error and no exception. My application was still waiting for incoming data, though the connection became stalled and no more data can get into. At the end, I had to press Ctrl-C to stop my application. Gist link: https://gist.github.com/nidev/720ecd32428cfdeb0868

Finally, I read [Twitter streaming API document](https://dev.twitter.com/streaming/overview/connecting), and found this phrase.

> Set a timer, either a 90 second TCP level socket timeout, or a 90 second application level timer 
> on the receipt of new data. If 90 seconds pass with no data received, including newlines,
> disconnect and reconnect immediately according to the backoff strategies in the next section.
> The Streaming API will send a keep-alive newline every 30 seconds to prevent your application
> from timing out the connection. You should wait at least 3 cycles to prevent spurious reconnects in
> the event of network congestion, local CPU starvation, local GC pauses, etc.

My conclusions are (also see #381):
1. 'readpartial' blocks until it gets data. Restarting router while streaming may cause 'stall'.
2. 'readpartial' infinitely reads from the connection which has become invalid since router got restarted.
3. Timeout may be needed. Expiration of a timeout should close currenct connection and may raise an exception.

Please look [my solution](https://gist.github.com/nidev/334ccfebb7ce5362b4bc) which is uploaded to Gist and give me better idea to get over this problem. Thanks.

I've reproduced this problem on those Ruby versions.

> nidev@yuuki-yuuna ~ % ruby --version
> ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
> nidev@alarmpi ~ % ruby --version
> ruby 2.2.0p0 (2014-12-25 revision 49005) [armv6l-linux-eabihf]

**Comment by martini** [comment]
++

**Comment by e-serrano-r** [comment]
++
