### ISSUE TITLE
SSL certificate verification failure 

### ISSUE THREAD

**Issue by dimanyc** [sferik/twitter#666]
Trying to test my connection to the API by running `[client].user("gem")`, and I keep getting the SSL error:

    Twitter::Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

I've set the ENV[variable] , and tried creating an initializer, pointing to the `cacert.pem` no luck. I've tested this on Win and OSx machines.

**Comment by stve** [comment]
@dimanyc what environment variable are you setting? When I've gotten this error, I've solved it by setting `SSL_CERT_FILE=/path/to/cacert.pem`

**Comment by dimanyc** [comment]
@stve you're right! Turned out to be a typo in my SSL_CERT_FILE environment variable
