### ISSUE TITLE
Streaming a particular twitter user

### ISSUE THREAD

**Issue by mcifani** [sferik/twitter#670]
Using this example

topics = ["coffee", "tea"]
twitter_stream.filter(track: topics.join(",")) do |object|
  puts object.text if object.is_a?(Twitter::Tweet)
end

Which will stream for any words, how can this be converted to an individual user to track (for tweets).  Thanks

**Comment by stve** [comment]
hi @mcifani 

You have two options:

1. Initiate a [User Stream](https://dev.twitter.com/streaming/userstreams) for that user (you'll need to authenticate as them) at which point you can do `streaming_client.user`
2. [Follow them](https://dev.twitter.com/streaming/overview/request-parameters#follow) via the `filter` method: `streaming_client.filter(follow: user_id)`

The main difference between the two approaches is that a User Stream will provide you with more event types, while the follow approach will give you only public events (ie., tweets, retweets, etc.)
