### ISSUE TITLE
Implement Ads APIs

### ISSUE THREAD

**Issue by stve** [sferik/twitter#671]
Hi @sferik 

Presumably you saw that documentation was recently added for these APIs. Do you envision support for these endpoints residing inside the gem? TON support appears to be 2 endpoints while the Ads API is quite extensive though I haven't really perused all the documentation for either endpoint yet. We'd probably want to add support via separate clients, something like `Twitter::Ads::Client` and `Twitter::TON::Client`. But maybe i'm getting ahead of myself. Curious to hear your thoughts.

**Comment by sferik** [comment]
Slated for [v6](https://github.com/sferik/twitter/milestones/v6).

**Comment by thomas-holmes** [comment]
I have a business need for this functionality and have started working on implementing this.

I've love to contribute my on-going work on supporting this API to the project. I'll make a PR soon to get some early feedback if you're interested.

**Comment by thomas-holmes** [comment]
I should clarify, that I am currently working on the Ads API and not the TON api.

**Comment by sferik** [comment]
@thomas-holmes :+1: I was waiting to implement these APIs until users started demanding them. It’s great to hear you‘ve already started working on this. Looking forward to your pull request.

**Comment by sferik** [comment]
I’m going to move TON into a separate issue.

**Comment by mledom** [comment]
We are working on the implementation as well. We haven't started any besides getting oauth working. @thomas-holmes how is the progress going on the ads api?

**Comment by thomas-holmes** [comment]
@mledom It's going well. My progress is in https://github.com/sferik/twitter/pull/687

It's pretty barebones but it does work. I haven't had much time lately to finish the last of it, but I'll try to get to it soon.

**Comment by mledom** [comment]
@thomas-holmes thanks for the update and the ref to the todos. We have been using it for the last couple days. Everything is working great so far!

**Comment by sferik** [comment]
This may be relevant to your interests: https://github.com/twitterdev/twitter-ruby-ads-sdk

**Comment by sferik** [comment]
If Twitter (with a capital T) is going to maintain their own version of this, I don’t see any reason to include it in this library.

**Comment by stve** [comment]
The Ads API has been in a steady state of flux over the past ~6 months. Twitter has continued to maintain their gem alongside the API changes.

I'm inclined to point others at Twitter's SDK vs. try to support the Ads API as part of this library going forward.

**Comment by sferik** [comment]
@stve I agree.

**Comment by stve** [comment]
I added a link to the SDK in the README fa916498783963f7be59e60bfe56b799a1494aca
