### ISSUE TITLE
Cut new 5.14 gem version?

### ISSUE THREAD

**Issue by outoftime** [sferik/twitter#672]
There was a [security vulnerability in the `http` gem](https://groups.google.com/forum/#!topic/ruby-security-ann/OLZxzGAFBig) which has been fixed in http 0.7.3—would you mind cutting a new gem version with the dependency updated? I'm able to use the `5-stable` branch from this repo just fine but it'd be nicer to grab the gem from rubygems.

**Comment by elhu** [comment]
:+1:, we're facing the same problem.

**Comment by sferik** [comment]
The `http` gem [backported](https://github.com/httprb/http.rb/pull/183) the security fix to [the `0-6-stable` branch](https://github.com/httprb/http.rb/tree/0-6-stable) and [released version 0.6.4](https://github.com/httprb/http.rb/commit/f21fdc30e16f88ff7a9fd09a8dd7dd948e9bb9a0), so releasing a new version of the `twitter` gem is not necessary.
