### ISSUE TITLE
Option to use string version of id

### ISSUE THREAD

**Issue by subvertallchris** [sferik/twitter#676]
Twitter's API returns IDs in both Fixnum and String versions but it looks like the gem always sets `id` instance method to return the Fixnum version. Is there an easy way to get this without calling `to_s` on the id? If no, it'd be nice if there was a config setting to use the String versions of IDs when instantiating new objects.

**Comment by sferik** [comment]
Why do you want to use the string version?

**Comment by subvertallchris** [comment]
Really long ints cause problems with Javascript. Twitter's API docs on IDs open by covering the issue [here](https://dev.twitter.com/overview/api/twitter-ids-json-and-snowflake).

In my case, when we return saved Twitter data to from database, our front-end app starts rounding down all of the IDs so we're forced to call `to_s` or convert to String before saving to the database or when returning the data. It's kind of silly since the API provides the data that we already need.

**Comment by sferik** [comment]
[When this was requested in the past](https://github.com/sferik/twitter/pull/380), I’ve argued that you can easily call `to_s` if you need a string representation of an integer. This is the Ruby way. I’d prefer not to get into the business of making changes to it to accommodate interoperability with JavaScript (or any other language).

Why don’t your JavaScript clients talk directly to the Twitter JSON API? It seems inefficient to convert JSON to Ruby and then back to JSON.

**Comment by subvertallchris** [comment]
Unnecessary type conversion is a problem, though, and if the data is already there, why not give the user the option to use it instead of forcing type coercion on them? `to_s` is inexpensive but it's not free.

JavaScript clients talk to our API, which pulls from a database that generates reports about data collected from Twitter.

**Comment by sferik** [comment]
> Unnecessary type conversion is a problem, though, and if the data is already there, why not give the user the option to use it instead of forcing type coercion on them? `to_s` is inexpensive but it's not free.

There is also a cost to adding an maintaining a method on the `Twitter::Tweet` object and presumably other all other objects whose ID space exceed 32-bits. For example, [list IDs crossed the 32-bit boundary about 1 year ago](https://blog.twitter.com/2013/list-ids-become-64-bit-integers-early-2014). At the time, this change in the Twitter API required no update to the gem. If we implemented this change, future objects that cross this barrier would require an update to this library. You’re asking me to accept that maintenance burden.

> JavaScript clients talk to our API, which pulls from a database that generates reports about data collected from Twitter.

In this case, it should be the responsibility of your API server to provide data in a format that is suitable to your API clients, not the responsibility of this library.
