### ISSUE TITLE
Twitter::Error::BadRequest

### ISSUE THREAD

**Issue by Sergiobzn** [sferik/twitter#684]
Hi!

I'm testing the gem and I'm not able to post tweets. 

I tested my app with curl commands that provide twitter api for testing and it run perfectly. So I think that my consumer keys / access tokens are correct.

I used that code:
client_twitter = Twitter::REST::Client.new do |config|
      config.consumer_key        = 'aaaa'
      config.consumer_secret     = 'aaaa'
      config.access_token        = 'aaaa'
      config.access_token_secret = 'aaaa'
    end
    client_twitter.update("Testing Testing!")

I've regenerated my keys and still recieving the same error:

Twitter::Error::BadRequest: Bad Authentication data.
	from /home/bzn/.rvm/gems/ruby-2.2.0/gems/twitter-5.14.0/lib/twitter/rest/response/raise_error.rb:15:in `on_complete'
	from /home/bzn/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
	from /home/bzn/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
	from /home/bzn/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
	from /home/bzn/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'
	from /home/bzn/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/request/multipart.rb:14:in `call'
	from /home/bzn/.rvm/gems/ruby-2.2.0/gems/twitter-5.14.0/lib/twitter/rest/request/multipart_with_file.rb:17:in `call'
	from /home/bzn/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /home/bzn/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /home/bzn/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
	from /home/bzn/.rvm/gems/ruby-2.2.0/gems/twitter-5.14.0/lib/twitter/rest/request.rb:33:in `perform'
	from /home/bzn/.rvm/gems/ruby-2.2.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:51:in `perform_request'
	from /home/bzn/.rvm/gems/ruby-2.2.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:73:in `perform_request_with_object'
	from /home/bzn/.rvm/gems/ruby-2.2.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:65:in `perform_post_with_object'
	from /home/bzn/.rvm/gems/ruby-2.2.0/gems/twitter-5.14.0/lib/twitter/rest/tweets.rb:158:in `update!'
	from /home/bzn/.rvm/gems/ruby-2.2.0/gems/twitter-5.14.0/lib/twitter/rest/tweets.rb:128:in `update'

**Comment by jose8a** [comment]
Assuming the 'aaaa' in your code above are just place-holders for the actual keys your code looks fine to me.  Only thing that comes to mind is the permissions that you've set on Twitter for your app.  Make sure that you have allowed 'Read and Write' permissions.  I had to change that on my app at some point because I initially had it at 'Read only'.  I can't remember what the default is, but I'm guessing it's set to 'Read only' unless you change it.

**Comment by Sergiobzn** [comment]
Access Level Read, write, and direct messages (modify app permissions) 
:(

**Comment by jose8a** [comment]
Sorry, I'm out of ideas.  I'm facing similar authentication problems with Devise/Omniauth, so I sympathize.  Hope someone else can come along to give you other ideas to fix your issue.

**Comment by Sergiobzn** [comment]
Hi, well.

I did my method to post tweets and then I saw the gem code.

I've changed the bearer_token_credentials_auth_header method in headers.rb to:
    token = @client.consumer_key + "&" + @client.consumer_secret
As twitter documentation says: https://dev.twitter.com/oauth/overview/creating-signatures

Now it works fine for me. 
I'll do a pull request
Sorry for my english.
