### ISSUE TITLE
How to do OOB authentication?

### ISSUE THREAD

**Issue by McOmghall** [sferik/twitter#691]
I'm trying to set up a twitter bot using one of my apps on other account (both the account and the app are mine, but the app is in a different account). Is there any way to retrieve my access_token and access_token_secret with this gem or the `t` app?

**Comment by sferik** [comment]
This gem isn’t designed to handle authentication; it assumes you’ve already acquired an OAuth token. If you’re looking for an example of how to do out-of-band authentication, there’s some code to handle that in `t`: https://github.com/sferik/t/blob/879bb831b716a98e8bbce4cc1058720216646a15/lib/t/cli.rb#L969-L981.
