### ISSUE TITLE
Implement Collections API

### ISSUE THREAD

**Issue by stve** [sferik/twitter#699]
https://dev.twitter.com/rest/collections

**Comment by bitops** [comment]
Do you guys know when this support is coming?

**Comment by stve** [comment]
hi @bitops, so far neither @sferik nor I have had much time to work on this just yet. Pull requests welcome :wink:

**Comment by rkingrum** [comment]
#782 added slight collection support in case you really need it.  Fairly big changes will need to be made in order to get full support, but this should do the job if you need something simple.
