### ISSUE TITLE
rdoc fails with ruby 1.9.3

### ISSUE THREAD

**Issue by dmlogs** [sferik/twitter#701]
`(RDoc::Error) unknown type of %string "i"`

The gem successfully installs flagged with `--no-document`.

**Comment by sferik** [comment]
Works for me: 
![screen shot 2015-09-01 at 16 22 52](https://cloud.githubusercontent.com/assets/10308/9606795/ce81d050-50c5-11e5-9c95-3d0576099f1f.png)

Can you please provide more details reproduction steps?

For what it’s worth, this is the last release that will support Ruby 1.9.3, so you make want to take this opportunity to upgrade to 2.0.0 or later.

**Comment by stve** [comment]
Closing as this has been open since June with no response. @dmlogs if this is still a problem, please feel free to reopen the issue.
