### ISSUE TITLE
update_with_media is deprecated per twitter api

### ISSUE THREAD

**Issue by jarblz** [sferik/twitter#702]
The update_with_media endpoint has been deprecated. I could not find any examples of using the update endpoint with an uploaded media_id listed anywhere.  What is the preferred method of updating_with_media currently?

Maybe this is how it should be done:

<pre>
media_ids = %w(/path/to/media1.png /path/to/media2.png).map do |filename| 
 client.upload File.new filename
end

tweet = client.update "tweet text", {media_ids: media_ids.join(',')}
</pre>

per <a href=https://github.com/sferik/twitter/issues/638>this issue</a>

**Comment by sferik** [comment]
Even though Twitter’s `POST statuses/update_with_media` endpoint has been deprecated, this library has maintained compatibility by using the new `POST statuses/update` endpoint in the existing interface.

[Here’s an example of how to post an update with multiple images.](https://github.com/sferik/twitter/blob/master/examples/Update.md)

**Comment by Yaroslav-F** [comment]
Hi, Erik, thanks a lot for your commitment.

Example above does not seem to work, I am getting the same error as described here #638 .

In the nutshell:

```
The following work:

client.update_with_media("tweet text",media.first) # successful
client.update_with_media("tweet text",media.last) # successful
This does not:

client.update_with_media("tweet text",[media.first])
```

So either documentation or the code should be updated, what do you think?

Thanks
