### ISSUE TITLE
Null Object is hard to work with / breaks other gems

### ISSUE THREAD

**Issue by andrewvc** [sferik/twitter#704]
The `Twitter::NullObject` is tricky and hard to reason about. I ask that you replace its uses with a plain `nil`. I encountered this pain when I tried to use it with JrJackson and it created the following issue: https://github.com/guyboertje/jrjackson/issues/39 .

**Comment by paracycle** [comment]
Would it not be better to report this in https://github.com/avdi/naught which is what seems to be causing the issue in the first place?

**Comment by paracycle** [comment]
BTW, it seems the problem is actually with JrJackson as I point out here: https://github.com/guyboertje/jrjackson/issues/39#issuecomment-114635667

**Comment by andrewvc** [comment]
@paracycle fair points. But I do think that rubygems should probably not return `Naught`, but a plain nil. It's fine to use that stuff internally, or on a closed project, but for an API it seems to be a choice that can cause pain due to its sheer oddity.

**Comment by andrewvc** [comment]
@paracycle any updates on your thinking here?

**Comment by paracycle** [comment]
@andrewvc Personally, I don't see a problem with returning an instance of a `BasicObject` that serializes properly and responds to all the messages that you'd expect it to respond to (duck-typing, remember). Null object pattern is a sound and widely accepted practice that actually helps API consumption.

However, since @sferik is the one who chose to implement the null object pattern, I think it would be more appropriate if he weighed in.

**Comment by andrewvc** [comment]
@paracycle I think the principle here is that if you're releasing a public API you want to to abide by language conventions. I think that using a special `nil` object is highly unusual. I can't think of a single other gem I've seen in my nearly 10 years of ruby that exposed a special nil as a public API. Would love to see @sferik 's thoughts here as well.

I do remember when the `Naught` gem came out ,and it was a time when meta-programming monkey patching and other bits of trickery were considered more positive. However, I think the ruby community has moved on from that point. It's better to be regular and predictable that highly customized and irregular.

**Comment by andrewvc** [comment]
I'll also add that I just don't see the value of using `Naught` here. What benefit is there in exposing this unusual null object to the user? Is the confusion outweighed by some utility? Most users will just be confused when they see it.

**Comment by sferik** [comment]
Using a null object was suggested by @krainboltgreen as a solution to https://github.com/sferik/twitter/issues/415. While it resolved that issue, it has caused [various other issues](https://github.com/sferik/twitter/search?q=Twitter%3A%3ANullObject&type=Issues), mostly related to serialization. I’m not sure which is worse.

I must admit, I hadn’t thoroughly considered serialization when designing this library. I assumed that anyone who wanted Twitter data in a serial format would talk directly to the Twitter API, rather than parsing a string into a Ruby object and then back into a string. Encoding a Twitter Ruby object with JrJackson is a particularly surprising use case because the Twitter API’s returns data as JSON. If you want tweets as JSON, I think you should be talking to the Twitter API directly, unless I’m misunderstanding your use case.

**Comment by andrewvc** [comment]
@sferik I think it's pretty common for an engineer to want to use a ruby gem as a DSL for interacting with an API. I think that's far more common than using a generic REST or HTTP library to pull twitter data.

For most users the efficiency gains are dwarfed by the inconvenience of interacting directly with the API.

Additionally, a gem like yours has actions nicely encoded as methods vs. something more generic.

**Comment by andrewvc** [comment]
WRT #415, if twitter sometimes returns nulls I think that's not really something a library like this should be responsible for. It also means that programmers may expect their code to fail in that spot, and that will be prevented by the special null.

**Comment by sferik** [comment]
I’ve [previously discussed and considered](https://github.com/sferik/twitter/pull/474#issuecomment-29550567) splitting this gem into two parts: one which merely establishing a connection to the Twitter API and returns raw data as a `String` and one which consumes those JSON strings, parsing them into useful Ruby objects. Then, you wouldn’t need to re-serialize the data, you could just use the raw strings returned by the first gem.

As I said in that comment, this would be an ambitious project, so I’m not sure I’d have time to take it on by myself at the moment, but if you’d like to start working on this, I believe that would be a good design that would address both problems.

**Comment by sferik** [comment]
> WRT #415, if twitter sometimes returns nulls I think that's not really something a library like this should be responsible for. It also means that programmers may expect their code to fail in that spot, and that will be prevented by the special null.

I’m not such a fan of client code that needs to check for `nil`s everywhere. That’s what the null object is designed to solve. I wouldn’t want to document all the places where Twitter might return `nil` (that is, `null` in JSON) and I wouldn’t want to change all the example code to replace `user.name` with:

```ruby
if user.nil?
  ""
else
  user.name
end
```

**Comment by andrewvc** [comment]
Well, this is all just my opinion. I think it's better for code to fail in a simple and expected way than to work in a confusing manner. There is nothing simple or expected about the `Naught` gem.

Regarding splitting the gem, I think that makes sense, but the one that returns strings should probably by default return ruby hashes with an option to put it in string mode.

**Comment by jordansissel** [comment]
> Encoding a Twitter Ruby object with JrJackson strikes me as a particularly strange use case because the Twitter API’s returns data as JSON.

For some background, the specific use case that originated this bug report is for Logstash. Logstash uses a "read, modify, write" style of behavior. Data comes in, gets modified, and gets shipped out to another destination. In this circumstance, it absolutely makes sense that we would parse the JSON data from Twitter into an object within ruby, do some work on that object, then serialize the result on the way out of the system. It's entirely possible we made some incorrect assumptions about the behavior of [tweet.to_hash](https://github.com/logstash-plugins/logstash-input-twitter/blob/master/lib/logstash/inputs/twitter.rb#L92), and if so, I'm happy to be corrected about such a thing :)

**Comment by krainboltgreene** [comment]
I really like the `Naught` gem and have been using it a lot. I wish it was a part of the STDLIB actually, since it's a rather simple implementation of the NullObject pattern. So +1 for using that.

I'm also a fan of splitting it into twitter-api and twitter-model (or some variant of those names.

**Comment by sferik** [comment]
> In this circumstance, it absolutely makes sense that we would parse the JSON data from Twitter into an object within ruby, do some work on that object, then serialize the result on the way out of the system.

I’d would expect preparing an object for serialization to be part of the “do work” phase of your process. For example, you could replace all null objects with `nil`s, if that is required to serialize objects in your preferred serialization format.

**Comment by sferik** [comment]
By the way, not all serializers have a problem with Naught objects.

```ruby
require "naught"
NullObject = Naught.build
Marshal.load(Marshal.dump(NullObject.new)).class
```

**Comment by jordansissel** [comment]
> not all serializers have a problem with Naught objects

Indeed. and the bug in JrJackson was just recently fixed. :)

> you could replace all null objects with nils

Indeed. I think the surprise was that `null` was represented by Naught and not `nil` and further that this tickled a bug in a serializer we used. That surprise lead to a "This is a weird thing" and this ticket being filed.

That said, I think the issue on our side is now resolved. Right, @andrewvc?

**Comment by andrewvc** [comment]
@jordansissel @sferik yes, the issue is fully resolved on our side.

I think we're just going to have to agree to disagree here wrt the Naught objects. IMHO it's tempting fate to replace something as basic as `nil`, but we could argue that for days.

**Comment by jordansissel** [comment]
@andrewvc indeed!

@sferik Thanks for the background on why Naught was chosen! I didn't even know about that library until now. :heart:

**Comment by sferik** [comment]
> I think we're just going to have to agree to disagree here wrt the Naught objects. IMHO it's tempting fate to replace something as basic as `nil`, but we could argue that for days.

For what it’s worth, the inventor of `nil` agrees that it’s a bad idea and should not be part of any modern programming language. I’d highly recommend watching the talk [Null References: My Billion Dollar Mistake](http://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare) by Tony Hoare.

**Comment by andrewvc** [comment]
@sferik while I agree that null is an issue, I think that Naught handles it weirdly, and trades one set of issues for another. To truly fix null issues languages like Haskell and Kotlin have more robust solutions.

**Comment by stve** [comment]
@andrewvc @jordansissel I didn't dive into the logstash code, but my guess is you are using a streaming client? If so, I've made some changes for inclusion in v6 of the gem that I think will make things easier for you. 

In particular, you can override the message parser that serializes JSON into Twitter objects. By overriding, you could create a generic parser that just returns the serialized JSON instead. Relevant code: https://github.com/sferik/twitter/commit/973657e943561116cb43d6c76cd9df707556fa0c and https://github.com/sferik/twitter/commit/e6734ec38da0819d151663b05fc31796b251b6aa

**Comment by saki7** [comment]
@sferik:
Ruby > 2.3 has got fancy `nil` improvement: the Safe Navigation Operator (`&.`), `ActiveSupport` has the `try` method too. (see: <http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/>)

This Null Object pattern makes it impossible to write fancy codes like below:

```ruby
real_user = tweet.quoted_tweet&.user || tweet.user
```

While I am aware of the design choice discussed in this issue above, I think this pattern could be resolved in a better way today; do you have any thoughts?

**Comment by oblivione81** [comment]
Just spent 15 minutes of my life trying to understand why a test, where I put an expectation for a field to be nil, was not passing, for no reason. Till I decided to print out the class names of the fields, and the one coming from the Twitter client was a NullObject.
Just wanted to add my 2 cents to this discussion :)
