### ISSUE TITLE
Get the twitter info by using token

### ISSUE THREAD

**Issue by rizalmuthi** [sferik/twitter#706]
Hi,
First of all, thank you for great work :)
I have question, i am building app with mobile app integration.
So basically, user can login using their twitter account in mobile.
What happen is, the mobile app will send the token to the backaned (rails)
Is there anyway that I could get all the information of the user using the token? (like koala gem)

I dont see any docs related to this, or I might missed it.

Thank you

**Comment by boldijar** [comment]
Sup!
I'm doing the same thing.

```
# next params are coming from the request body
  token = params['token']  
      secret = params['secret']
      client = Twitter::REST::Client.new do |config|
        config.consumer_key = ".. "
        config.consumer_secret = ".. "
        config.access_token = token
        config.access_token_secret = secret
      end
      verify = client.verify_credentials
      username = verify.screen_name
```

And you have the username here, render the verify object as response, and you'll see what other fields are left.
