### ISSUE TITLE
Getting expanded URI

### ISSUE THREAD

**Issue by choonggg** [sferik/twitter#710]
I am having trouble getting expanded_uri from 

tweet => #<Twitter::Tweet id=620685745150242820>
tweet.uris

How do I get the expanded_uri from tweet.uris?

**Comment by stve** [comment]
Are you certain that the tweet you are looking at has entities? You can use predicate methods to verify:

```
tweet.entities?
tweet.uris?
```

You can see the full list of methods [here](http://www.rubydoc.info/gems/twitter/Twitter/Entities)

**Comment by choonggg** [comment]
Hi @stve, thanks for clarifying and I realised this is quite an old question. Let's close it. :smiley:
