### ISSUE TITLE
Support for Twitter Ad

### ISSUE THREAD

**Issue by ianks** [sferik/twitter#711]
I am looking to integrate Twitter Ads analytics into an app I am working on. I was curious if this Gem would be open to supporting ads api access in the future? I would be interesting in adding that feature to this Gem, but would like to know beforehand if a PR with Ads API integration, given that is would well-written, would be accepted.Thanks is advance :smile:

**Comment by stve** [comment]
Development on this is in progress and slated for release in v6 of the gem, you'll want to keep track of #687
