### ISSUE TITLE
allow tiny bug fix version differences for simple_oauth

### ISSUE THREAD

**Issue by pravi** [sferik/twitter#713]
Currently the dependency requirement is 'simple_oauth', '~> 0.3.0' can this be changed to ~> 0.3? Does every tiny bug fix release break twitter?

**Comment by sferik** [comment]
Specifying the `simple_oauth` dependency as `~> 0.3.0` allows you to upgrade to any 0.3.x release less than 0.4, since such a release may include larger changes. What’s the actual problem you’re having? Are you unable to upgrade to `simple_oauth` version 0.3.1?

**Comment by pravi** [comment]
Bundler could not find compatible versions for gem "simple_oauth":
  In Gemfile:
    twitter (= 5.14.0) ruby depends on
      simple_oauth (~> 0.3) ruby
Could not find gem 'simple_oauth (~> 0.3) ruby', which is required by gem
'twitter (= 5.14.0) ruby', in any of the sources.

Actually, its a bug in simple_oauth debian package, it did not install the gemspec file. Sorry for the noise.
