### ISSUE TITLE
Sending media via DM

### ISSUE THREAD

**Issue by eanie** [sferik/twitter#716]
Apologies, I know this isn't an issue, but it seems dramatically difficult, even through the Twitter api directly. Does anyone have an example of sending and image along with a DM tweet. It's driving me crazy

**Comment by stve** [comment]
@eanie I don't believe this is possible. The [API documentation](https://dev.twitter.com/rest/reference/post/direct_messages/new) gives no indication that anything other than `text` can be sent as part of a DM. If you find information to the contrary feel free to reopen this issue.
