### ISSUE TITLE
Not possible to get quoted_tweet?

### ISSUE THREAD

**Issue by greyguy123** [sferik/twitter#717]
I noticed you guys commited some changes a while ago for it but did you do anything in practice? I'm trying to access quoted_status but always crashes my script

**Comment by sferik** [comment]
Can you please provide more details about your script? What line of code is producing an error? What error is it producing? What version of this library are you using? What version of Ruby are you using? What operating system are you using? The more information the better.

Ideally, you’d provide a minimal snippet that reproduces this issue.

I was unable to reproduce this issue using `twitter` version 5.14.0 on Ruby 2.2.3 on Mac OS X 10.10:

```ruby
tweet = client.status(637619702639030273) #=> #<Twitter::Tweet id=637619702639030273>
tweet.text #=> "@olivierlacan That’s what got me thinking about this (https://t.co/ONOdkrh2Up)—but the new MacBook is not addressing low-end of the market."
tweet.quoted_status #=> #<Twitter::Tweet id=637587257067745280>
tweet.quoted_status.text # => "@gernot @gruber The gap between the dual-core Intel Core M in the MacBook and the A9X in the upcoming iPad will be small—and it’s narrowing."
```

**Comment by stve** [comment]
Closing as this has been open since August with no response. @greyguy123 if this is still a problem, please feel free to reopen the issue.
