### ISSUE TITLE
#search won't retrieve all tweets for hashtag

### ISSUE THREAD

**Issue by vinagrito** [sferik/twitter#723]
I apologize in advance if this is not the correct place for this but I just didn't know where else to go.

Last month (July 2015) I created a hashtag called __[#danTest](https://twitter.com/search?q=%23danTest&src=typd)__ and it all worked fine when I was querying it. Now (August 2015) I am not getting the tweets created in July only the ones I added this month. So If I call:
```ruby
$twitter_client.search("#danTest).take(5)
=> [#<Twitter::Tweet id=633210895934562304>, #<Twitter::Tweet id=633210596503257088>, #<Twitter::Tweet id=632929337457672192>]
```
There are 2 tweets that are staying out of this response. What am I missing?

thx

**Comment by stve** [comment]
The search API is severely limited by Twitter. From their [documentation](https://dev.twitter.com/rest/reference/get/search/tweets):

> Please note that Twitter’s search service and, by extension, the Search API is not meant to be an exhaustive source of Tweets. Not all Tweets will be indexed or made available via the search interface.

There's also a [data availability window](https://dev.twitter.com/rest/public/search) which is most likely what's impacting your results:

> Also note that the search results at twitter.com may return historical results while the Search API usually only serves tweets from the past week.
