### ISSUE TITLE
Turn off "auto-loading" of next page

### ISSUE THREAD

**Issue by zverok** [sferik/twitter#724]
Hey. 
I've recently updated from ancient version of twitter gem and was really incredibly surprised with SearchResults auto-loading next page behavior.

At first, "transparent enumeration" seems witty and ruby-ish thing, yet... Let's look at the simplest case:
```ruby
client = Twitter::REST::Client.new(....)
client.search('ruby').count
```
(Don't try this at home!)

What can be expected from such a simple piece of code? For me, one of two things:
1. Either "count of results received by 1 API call"
2. Or "count of all available results for 'ruby' query" (only in case, if such a count can be received with 1 API call, e.g. if Twitter has corresponding endpoint)

What will happen in fact? The very strange thing: `Enumerable#count` will be called, which implicitly calls `#each`, which, in our case, will silently grab half of the Internet for just returning one number. I don't think this behavior produces least surprise.

More practical example: imagine Resque/Sidekiq task, which is scheduled to grab one page of search results, then (if next page needed) reschedule itself in future (for rate limiting). It seems very common approach to gather social media information.

So, what this task needs from search results?
1. get "current page" tweets (which is no easy way to do: either it should use raw `#to_h`, or do `first(page_size)`)
2. get "if next page exists" and "what's next page address", which is no ease also.

I'm really disappointed and would be really happy to know some reasonable ways to work with SearchResults in a more convenient way.

**Comment by sferik** [comment]
If you want “raw” access to search results, you can call `to_h` on it, as you suggest above.

The data you seek is in the `:search_metadata` hash:

```ruby
search_results  = client.search('ruby')
search_metadata = search_results.to_h[:search_metadata]
search_metadata[:count]        #=> 100
search_metadata[:next_results] #=> "?max_id=639478378723168255&q=ruby&count=100&include_entities=1"
```

You say this is not easy. How would you propose making it easier?

**Comment by zverok** [comment]
See, I understand about `#to_h`, as I've already written:
> ...which is no easy way to do: either it should use raw `#to_h`...

The thing is I _don't_ want raw data. I want nicely wrapped objects easy to work with.

What I'm talking about is current state of things both unnecessary "easy" (its easy to do dumb thing unintentionally, like in my first example) and unnecessary complicated (like in my second example).

I'm confident most API wrappers should, in first place, do access to API simpler and more ideomatic for target language -- while providing all the features source API provide.

The way it seems reasonable for me is next:

```ruby
# Current page
result = client.search('ruby', count: 30)
result.count # => 30
result.to_a # => Array of 30 Tweets
result.each do |tweet|
  # iterating through 30 tweets
end

# Next page
results.next_page? # => true
results.next_page_params # => {max_id: ..., since_id: ..., q: ...}

next_page = client.search(results.next_page_params) # => SearchResults
# and (optional) shortuct of above:
next_page = results.fetch_next_page # => SearchResults
```

That's it.

**Comment by sferik** [comment]
What you’re describing is the old interface to this gem. It doesn’t work like that anymore. The idea was to further abstract away the HTTP layer. That said, you can get the behavior you’re looking for with a very small modification to your code:

```ruby
# Current page
results = client.search('ruby').take(30)
results.count # => 30
results.to_a # => Array of 30 Tweets
results.each do |tweet|
  # iterating through 30 tweets
end
```

If you want to fetch more than 30 results, you don’t need to know anything about pages or URLs or params. You can just ask the object for more results. Another nice feature of `Twitter::SearchResults` being `Enumerable` is that it can be converted to an `Enumerator` that yields results.

```ruby
results = client.search('ruby').to_enum
30.times do
  tweet = results.next
  # do something with the first 30 tweets
end
30.times do
  tweet = results.next
  # do something with the next 30 tweets
end
```

When you try to yield the 101st tweet, the enum will transparently fetch 100 more tweets.

---

I understand that upgrading from an older version of this library may have been a jarring experience for you. I did my best to ease the transition from version 4 by [documenting the changes in an upgrade guide](http://www.rubydoc.info/gems/twitter/5.14.0#What_s_New_in_Version_5_) when version 5 was released. I’d encourage you to read that guide, if you haven’t yet. The benefits of the `Enumerable` interface are enumerated there, so I won’t repeat them here. For those who were familiar with the old interface, the changes to the interface may come as a surprise, but for new users of the library, who are familiar with Ruby’s `Enumerable` interface, it should seem quite familiar and easy to use.

It is true that calling `#count` on an `Enumerable` may be an expensive operation. Unfortunately, Twitter does not provide any other way to determine the total number of search results. Of course, if the total number of results for a query is under 100, `#count` returns instantaneously, so it is as optimized as possible.

Version 5 of this library was in pre-release from September to November 2013. That would have been a good time to test out the new interface and provide feedback. Two years later, that ship has sailed. The old interface is gone and it’s not coming back.

If you want to keep using an older version of the gem, you’re free to do so—but I won’t be maintaining it.

**Comment by zverok** [comment]
Fair enough. 
Sorry for this rant, just was VERY surprised with difference in mental models.
Thanks for your work!
