### ISSUE TITLE
Tweets containing hashtag not fetching - returns nil only

### ISSUE THREAD

**Issue by pbharadiya** [sferik/twitter#729]
Hello,

I tried this.
<code>
client.search("#Uxrep").first => nil </code>
<code>
client.search("#trymyuiEDU").first => returns correct data
</code>

why I am unable to fetch tweets for "#Uxrep" even if tweets exist when I search in twitter directly?

**Comment by stve** [comment]
Hi @pbharadiya, There are several reasons why this could be happening, Please see my response on #723. Thanks.

**Comment by pbharadiya** [comment]
Sorry for reopening. Just wanted your help.
As you suggest, I guess, in my case, this may be an issue.
"Not all Tweets will be indexed or made available via the search interface."

So is there any other way/work around to anyway fetch tweets in this case using our gem?

**Comment by stve** [comment]
Not reliably via the REST API. You could stream tweets into a datastore and build a search interface off of that.

**Comment by pbharadiya** [comment]
Ok. Thank you very much for your really quick help!
