### ISSUE TITLE
Timestamp converted differently when using the to_json method on the Tweet object than tweet.created_at.to_json

### ISSUE THREAD

**Issue by andrewchen5678** [sferik/twitter#730]
When I use `tweet.to_json` method to convert to json, the timestamp ends up to be in a format different than iso8660. However, when I convert the timestamp directly to json, it gets the right format. It seem to be something is up with the to_hash method.

```
[9] pry(main)> tweet.to_json
=> "{\"created_at\":\"Fri Sep 18 12:39:13 +0000 2015\",\"id\":644853178584793089,\"id_str\":\"644853178584793089\",...
[10] pry(main)> tweet.created_at.to_json
=> "\"2015-09-18T12:39:13.000+00:00\""
[11] pry(main)> tweet.created_at.class
=> Time
[12] pry(main)> tweet.to_hash
=> {:created_at=>"Fri Sep 18 12:39:13 +0000 2015",
 :id=>644853178584793089,
 :id_str=>"644853178584793089",
 :text=>
  "Have been kept on getting the \"Unable to connect to iTunes purchases\" error since yesterday after opening #iTunes. http://t.co/m4o1kPDWAg",
```
It should be  "\"2015-09-18T12:39:13.000+00:00\"" all the time instead.

**Comment by stve** [comment]
When you call [`to_hash`](https://github.com/sferik/twitter/blob/513206fd127266d8e65aeece4fd6dfa44e9b8d3f/lib/twitter/base.rb#L12-L15) you are basically just asking for the underlying JSON serialized attributes of the object to be returned.

[`Twitter::Creatable#created_at`](https://github.com/sferik/twitter/blob/513206fd127266d8e65aeece4fd6dfa44e9b8d3f/lib/twitter/creatable.rb#L8-L14) is a convenience method for accessing the `created_at` as a Time object as you've observed. 

We support a number of convenience methods on top of the underlying response, but the `attrs` are there for you to tap into the raw response data if/when needed.
