### ISSUE TITLE
Request: update_with_media using image url and/or TempFile

### ISSUE THREAD

**Issue by danielbonnell** [sferik/twitter#731]
It would be very useful if the `update_with_media` method accepted a URL and/or TempFile in addition to a `File` object.

**Comment by qq99** [comment]
@danielbonnell 

```ruby
require 'open-uri'

images = image_urls.map do |image_url|
  uri = URI.parse(image_url)
  uri.open
end

client.update_with_media('foo', images)
```

where `image_urls` looks like `['http://example.org/somepic.jpg', ...]`

I've found that the above works on latest master :)  I have also noticed it can fail, but so far that's only been when I've attempt to tweet the same image multiple times with the same image attachment -- could be Twitter trying to detect spam and limit it?

**Comment by sferik** [comment]
`Tempfile` should also work, since it is a descendant of `File`. Have you tried it?

**Comment by danielbonnell** [comment]
@qq99 Thanks! That's what I ended up doing in my code to get it to work. So far I haven't had any trouble except when trying the same image more than once in a row like you said. @sferik I recall trying it with `Tempfile` awhile back and not getting through.

**Comment by apalmblad** [comment]
Note that the code from @qq99 will not work out of the box with links to files less than 10k in size.

The client requires IO objects that respond to `to_io` and StringIO does not respond to `to_io`.  OpenURI uses StringIO for files less than `OpenURI::Buffer::StringMax`, default value of 10k. You can get around it with some *ugly* code:
```   
if OpenURI::Buffer.const_defined?('StringMax')
  old_max = OpenURI::Buffer.const_get( 'StringMax' )
  OpenURI::Buffer.send( :remove_const, 'StringMax' ) # avoid warnings
  OpenURI::Buffer.const_set( 'StringMax', 0 )
end
URI.parse( link ).open
if OpenURI::Buffer.const_defined?('StringMax')
  OpenURI::Buffer.send( :remove_const, 'StringMax' ) 
  OpenURI::Buffer.const_set( 'StringMax', old_max )
end
```

Although it seems https://github.com/sferik/twitter/blob/v5.15.0/lib/twitter/rest/tweets.rb#L229 has been removed in master, so hopefully StringIO issues become a non issue on the next release.

**Comment by Tybi** [comment]
When I try to upload with the @qq99 response I get this error Twitter::Error::Unauthorized: Could not authenticate you. But if I just upload without media it's work, does anyone has the same problem.

**Comment by mscoutermarsh** [comment]
@tybi I have the same problem. If I upload using the `media_data` param, then it works. But I had to modify `Media#upload` to do it.

```Ruby
file = Base64.encode64(open(image_url).read)
```

```Ruby
      def upload(media, options = {})
        # fail(Twitter::Error::UnacceptableIO.new) unless media.respond_to?(:to_io)
        url_prefix = 'https://upload.twitter.com'
        path = '/1.1/media/upload.json'
        conn = connection.dup
        conn.url_prefix = url_prefix
        headers = request_headers(:post, url_prefix + path, options)
        # options.merge!(:media => media)
        conn.post(path, options) { |request| request.headers.update(headers) }.env.body[:media_id]
      end
```
