### ISSUE TITLE
Twitter SSL connection error received periodically

### ISSUE THREAD

**Issue by jeremyhaile** [sferik/twitter#733]
I periodically receive the following error when calling `client.user` using a user's oauth token. 

`OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A`

It is difficult to reproduce as I do not receive this error consistently. However, it has happened in production for me 322 times in the last 30 days, according to my error tracking service.

My app is running on Heroku using the latest cedar-14 stack. I also contacted Heroku and they confirmed I'm using the latest SSL certificates and suggested I open an issue here.

**Comment by stve** [comment]
hi @jeremyhaile I traced the error message back to ruby/openssl: https://github.com/ruby/openssl/blob/fccd05e12819ad23aa4c26d7e2f289bca77d8675/ext/openssl/ossl_ssl.c#L1305

My C is somewhat rusty, but it looks like this checks the response code after attempting a read. Did Heroku tell you what version of openssl is installed?
