### ISSUE TITLE
Rake Routes: Unitialized Constant Twitter

### ISSUE THREAD

**Issue by InsomniaNoir** [sferik/twitter#738]
I've been digging through StackOverflow but I cannot find a solution to this problem, though I know it's been a known issue in the past and I can't find a concrete answer. I run rake:routes and get the following:

`NameError: uninitialized constant Twitter
/Users/jrshafer/Documents/Development/kronoTweeter/config/initializers/twitter.rb:1:in`

This is based on the following initializer file built directly off the documentation with the use of Figaro and environment variables:

    client = Twitter::Client.new do |config|
      config.consumer_key        = ENV['CONSUMER_KEY']
      config.consumer_secret     = ENV['CONSUMER_SECRET']
      config.access_token        = ENV['ACCESS_TOKEN']
      config.access_token_secret = ENV['ACCESS_SECRET']
    end

**Comment by sferik** [comment]
Did you remember to add `gem 'twitter'` to your `Gemfile`?

**Comment by InsomniaNoir** [comment]
I did. It would seem I lost it somewhere in the shuffle of starting a new branch so I didn’t kill the work I did in oauth. **Sigh**

**Comment by stve** [comment]
@InsomniaNoir it appears that @sferik's suggestion solved your problem. If the problem persists, or you need additional help, feel free to ask more questions on the [mailing list](https://groups.google.com/forum/#!forum/twitter-ruby-gem).
