### ISSUE TITLE
oembed images/styling disappear after page loads

### ISSUE THREAD

**Issue by danielbonnell** [sferik/twitter#740]
I'm trying to use the Twitter gem's oEmbed method to display an embedded tweet in my Rails app. I have the following code in my template (`@tweets` is an array of tweet ids):

    <% @tweets.each do |tweet_id| %>
        <%= @company.twitter_client.oembed(tweet_id).html.html_safe %>
    <% end %>

Note, I've also tried passing in `omit_script: true` as a second argument to the `.oembed` method.

When I load up the page I see the tweet fully rendered as expected.  
![1](http://i.stack.imgur.com/2774z.png)

However once the page finished loading, all images/styling for the tweet disappears.
![2](http://i.stack.imgur.com/X7Fwr.png)

Now if I include the `omit_script: true` argument, the tweet appears without images/styling and remains that way once the page finishes loading.
![3](http://i.stack.imgur.com/NqgbY.png)

I've tried including the `widgets.js` snippet from the [Twitter docs](https://dev.twitter.com/web/javascript/loading) but no matter what I try, I can't get the properly rendered tweet to stay after the page finishes loading. I checked the console and there are no errors.

When I first tried this I only had one test tweet with an attached image. I then created a second tweet without an image. Now when I try it, I'm not able to get the rendered tweet on the page no matter what I try.

I've been looking through the docs/examples but the coverage for the `oembed` method is pretty sparse.

**Comment by stve** [comment]
Seems odd that it would render and then disappear. Do you have this running on a server where we can take a look? Could it be a browser plugin?

**Comment by dlo** [comment]
This is happening to me too, fwiw. @danielbonnell did you ever arrive at a solution?

**Comment by danielbonnell** [comment]
@dlo I didn't. The specs for the feature I was working on changed so I never pursued it further. If I ever come back to it and solve it I'll update this issue with what worked.

**Comment by dlo** [comment]
Weird. Well, I think I figured it out on my end. It was a Safari content blocker. Chrome too. Disabled them and the tweet appeared. ¯\_(ツ)_/¯
