### ISSUE TITLE
.update returns last tweet, not the duplicate

### ISSUE THREAD

**Issue by ponny** [sferik/twitter#743]
You can see the code here:
https://github.com/sferik/twitter/blob/master/lib/twitter/rest/tweets.rb#L127

In the event of a duplicate tweet, it returns the users last tweet and not the actual duplicate.  This is very misleading.  I suggest either throwing an error like the library used to or perferably somehow returning a reference to the tweet that the update would be a duplicate of.

**Comment by stve** [comment]
Hi @ponny, there are actually two methods here, `#update` is more passive and falls back to returning the last tweet sent by the user. Unfortunately, there is no mechanism by which to determine the duplicate - it's not passed back from the API. To raise an exception, the `#update!` method will raise a `Twitter::Error::DuplicateStatus`.
