### ISSUE TITLE
Twitter::Error::Unauthorized: Invalid or expired token.

### ISSUE THREAD

**Issue by adrianescat** [sferik/twitter#745]
I do not know why sometimes this happens with _some_ of my **twitter users**. I need to understand why _some of them_ have not problems in my app and others when i simple do
`client.friends` returns `Twitter::Error::Unauthorized: Invalid or expired token`.

I'm using it correctly:

```
def self.rest_client user
    Twitter::REST::Client.new do |config|
      config.consumer_key        = TWITTER_CONFIG['consumer_key']
      config.consumer_secret     = TWITTER_CONFIG['consumer_secret']
      config.access_token = user.oauth_token
      config.access_token_secret = user.oauth_secret
    end
  end
```

```
client = rest_client(user)
friends = client.friends
```

**Comment by stve** [comment]
Hi @adrianescat 

Were you able to determine what was causing this? Does it happen consistently to certain users? or is it intermittent?

**Comment by bobber205** [comment]
yeah more info would have been super helpful

**Comment by stve** [comment]
Closing due to lack of info. @adrianescat feel free to re-open.

**Comment by varshanihanth** [comment]
Unable to publish a Twitter post from my APP, it shows me invalid or expired token as error message, but in the backend, it showing as token didn't get Expired, 
Verified with Password change, Change in Twitter Handle, invalid Twitter password, revoking Access to the APP, but still, it is working

**Comment by bobber205** [comment]
@varshanihanth you do know this thread is closed right? Create a new one.
