### ISSUE TITLE
Twitter::Error::TooManyRequests: Rate limit exceeded

### ISSUE THREAD

**Issue by zackxu1** [sferik/twitter#747]
I've been using this gem for a while.
But suddenly, since last Friday 20 Nov 2015 afternoon (GMT), the program stopped getting any search results.  I'm getting

Twitter::Error::TooManyRequests: Rate limit exceeded

This problem has persisted for the past 5 days.

Clearly the error message is misleading, as I'm NOT exceeding the rate limit.
So either my credentials are expired or there're some issues with Twitter REST API.

Anyone else experienced this problem?

Thank you

**Comment by lamdan** [comment]
We ran into this same issue. If you're calling `to_a` or `each` on your results, you will end up fetching the next page of search results.

https://github.com/sferik/twitter/blob/master/lib/twitter/enumerable.rb#L13

We fixed this in our app by:

`query_results.attrs[:search_metadata][:next_results] = nil`
