### ISSUE TITLE
Retrieve User's Lists

### ISSUE THREAD

**Issue by zreitano** [sferik/twitter#750]
Is there a way to retrieve the lists created by a user. 

It seems that I can retrieve a list with the list id or owner/slug...but not solely with owner. 

I want to be able to do:
user = client.user
lists = user.lists

**Comment by PatrickWalker** [comment]
https://dev.twitter.com/rest/reference/get/lists/ownerships
Has a rest endpoint to do it.

This seems to be implemented currently in the rest client so

@client.owned_lists('sferik')

It says it tales a user object potentially as well so

user = client.user
lists = client.owned_lists(user)

Should work
