### ISSUE TITLE
Multiple user streams in 1 rake process?

### ISSUE THREAD

**Issue by cbetta** [sferik/twitter#751]
Has anyone ever tried to spawn multiple streams in one rake task? Seeing as Twitter Site streams wont be rolled out widely any day soon.

**Comment by stve** [comment]
Hi @cbetta, Provided you are streaming with unique credentials, I wouldn't think you'd have any issues running a stream in multiple threads or process. The gem is designed to be threadsafe.

The reason I mentioned unique credentials is that twitter has a single stream limitation, [per their documentation](https://dev.twitter.com/streaming/public):

> Each account may create only one standing connection to the public endpoints, and connecting to a public stream more than once with the same account credentials will cause the oldest connection to be disconnected.

**Comment by cbetta** [comment]
@stve tnx, I indeed would be running one per user. Any idea how to achieve this?
