### ISSUE TITLE
A straightforward method to retrieve tweet owner

### ISSUE THREAD

**Issue by nemoload** [sferik/twitter#757]
I was making a twitter bot which replies to a certain keywords based on tweets retrieved from user's mention timeline.
The problem I had is that I needed to add _@tweet_onwer_ before the reply tweet to his previous tweet which he had mentioned my bot there, I opened `Twitter::Tweet`  documentation and couldn't find anything returns the username of the tweet's owner which was very weird.
Anyway I opened the source code and found that _user object_ has the property I want, so I think the documentation should be edited to cover that detail or new reading methods to be added in  `Twitter::Tweet` class.

**Comment by stve** [comment]
@nemoload As you've observed, every `Twitter::Tweet` has a reference to `user` which will be a `Twitter::User` object.

Indeed, there is a fair amount of metaprogramming in there which makes it tricky to document in a way that Yard picks it up. We've discussed some improvements here and I think this will be something that gets better once we've had a chance to work through it. Thanks for bringing this to our attention.

**Comment by stve** [comment]
I realized there's an existing issue that addresses this, feel free to follow #601
