### ISSUE TITLE
deprecated API endpoint

### ISSUE THREAD

**Issue by 47primes** [sferik/twitter#760]
I am using version 5.16.0 in a project, but I notice it is using a deprecated endpoint for `update_with_media`. I see that in master `update_with_media` is using the 2-step process of uploading the media then posting to `update` with `media_ids`. I would like to know if the next version of the Twitter gem will use this process in favor of the deprecated API endpoint. If I may ask, is there a timeline for such an update?

Thanks!

**Comment by stve** [comment]
Hi @47primes, we definitely plan to support it, most likely in version 6, but as of yet it hasn't been worked on. Pull requests welcome :smile:
