### ISSUE TITLE
Is uploading a video supported?

### ISSUE THREAD

**Issue by jcsk** [sferik/twitter#761]
I've tried several ways of uploading a small mp4 video. But I get the following error from twitter:

Twitter::Error::BadRequest: The validation of media ids failed.

I'm not sure if the gem supports chunked video uploading: [https://dev.twitter.com/rest/public/uploading-media](https://dev.twitter.com/rest/public/uploading-media)

I've tried using twurl, and it works with the same file, so I know it's not a size, length, width/height, aspect ratio problem.

The twurl command (after auth) is along the following:

`twurl -H upload.twitter.com "/1.1/media/upload.json" -d "command=INIT&media_type=video/mp4&total_bytes=113004`

`twurl -H upload.twitter.com "/1.1/media/upload.json" -d "command=APPEND&media_id=707438900436930561&segment_index=0" --file filename.mp4 --file-field "media"`

`twurl -H upload.twitter.com "/1.1/media/upload.json" -d "command=FINALIZE&media_id=707438900436930561"`

`twurl "/1.1/statuses/update.json" -d "media_ids=707438900436930561&status=You get the point..."`

Let me know if I'm missing something. Thanks!

**Comment by jonmast** [comment]
Video upload support was added in #755. You need to be running master to get this though, it hasn't been back-ported to the stable branch.

**Comment by narlei** [comment]
@jonmast  Why only supports MP4 video file? There any way to send other formats?

**Comment by jonmast** [comment]
@narlei Twitter requires the video to be AAC encoded: https://dev.twitter.com/rest/media/uploading-media#videorecs

**Comment by faustoct** [comment]
fail trying to upload file with

    file = open('http://domain.com/file.mp4')
    client.upload(file,{status:'video upload'})

**Comment by mebre688** [comment]
the same  happen to me when i first try to uploading video my account. however you’ll be prompted if the selected video is not in a supported format. Maximum file size is 512MB. and Maximum video length is 2 minutes and 20 seconds.) See here for more details about formats.) https://support.twitter.com/articles/20172128 and https://dev.twitter.com/rest/public/uploading-media 
that may help !!

**Comment by danielbonnell** [comment]
Does anyone have a working example of how to upload a video using the chunked method using this gem? I've seen other examples using Bash, PHP, other libraries, etc, but nothing using this gem.
