### ISSUE TITLE
media type method?

### ISSUE THREAD

**Issue by chrisallick** [sferik/twitter#763]
```
search_results = twitter_client.user_timeline("bbc", {:count => 4})
search_results.each do |tweet|
  if tweet.media?
    tweet.media.each do |media|
      puts media.type
    end
end
```

does not work, but i'd expect it to what am i doing wrong? i want to know if the media is a photo or animated gif or video

**Comment by stve** [comment]
Hi @chrisallick, thanks for reporting this. `#type` wasn't an attribute we'd included on media objects. I've fixed this in master (77238b540edfbc76aa2f25bc4398c3dad8f55edb) so it'll be included in the next release.

**Comment by bianjingbulb** [comment]
this is not work

**Comment by bianjingbulb** [comment]
this gem is so difficult to use!
