### ISSUE TITLE
Would you make API URL configurable?

### ISSUE THREAD

**Issue by hellojinjie** [sferik/twitter#769]
for example
the API URL is:
https://stream.twitter.com/1.1/statuses/sample.json
would you make the host configurable.
like:
TWITTER_STREAM_HOST = stream.twitter.com:443
https://TWITTER_STREAM_HOST/1.1/statuses/sample.json

**Comment by stve** [comment]
Hi @hellojinjie is there a particular reason that you need this? We recently added proxy support which may be what you are after?

**Comment by hellojinjie** [comment]
@stve Thank you for your reply.

We can not reach twitter api directly in China.
I have tried proxy, it worked fine with REST api, but did not work with streaming api.
So, I set up a https relay proxy, here -> https://hellojinjie.com:444/1.1/statuses/user_timeline.json

to use this https relay proxy , i need to replace the host and port of the api endpoint.

**Comment by SmartHoneybee** [comment]
I would appreciate a configurable API URL since that might enable me to use this interface to talk to a GNU social instance. ([GNU social][] is the new StatusNet and an opensource approach to a decentralized twitter.)

[GNU social]: https://gnu.io/
