### ISSUE TITLE
`on_headers_complete': Twitter::Error::Unauthorized

### ISSUE THREAD

**Issue by ESSEC69** [sferik/twitter#770]
Hi Guys,
I'm using gem twitter, the REST part is working incredibly well
However coming to the Streaming part and calling for example users or sample
I get this error :

`on_headers_complete': Twitter::Error::Unauthorized

I have add a callback adress but nothing change.
Do you have any idea of what I can do ?
Thanks

**Comment by mcassiano** [comment]
+1

**Comment by burpingcow** [comment]
@ESSEC69 
figured it out?
