### ISSUE TITLE
oEmbed endpoint changed to publish.twitter.com

### ISSUE THREAD

**Issue by stve** [sferik/twitter#774]
Per [documentation change on 5/3](https://www.apichangelog.com/changes/1df28f75-4cf5-4346-a57a-9e8083174bee), the new endpoint is `https://publish.twitter.com/oembed`

the old endpoint (`https://api.twitter.com/1/statuses/oembed`) still appears to work (for now).

**Comment by rob-murray** [comment]
The new API also has [embedded timeline too](https://dev.twitter.com/web/embedded-timelines/oembed).
