### ISSUE TITLE
Search count returning max tweet requests

### ISSUE THREAD

**Issue by tahsini** [sferik/twitter#781]
A call to:
`client.search('from:example_user+OR+from:example_user2', count: 5)`

Results in the maximum number of tweets returned instead of limiting to 5 as expected

**Comment by rusikf** [comment]
:+1: but you can use attrs directly:
```ruby
res = client.search('from:example_user+OR+from:example_user2', count: 5)
res.attrs[:statuses].count
```

**Comment by stve** [comment]
@tahsini search results are eager loaded. If you want to limit to precisely `count` results, I'd suggest using [`Enumerable#take`](https://ruby-doc.org/core-2.4.0/Enumerable.html#method-i-take) like so:

```ruby
count = 5
search_results = client.search('from:example_user+OR+from:example_user2', count: count)
search_results.take(count).each do |tweet|
  puts tweet.text
end
```
