### ISSUE TITLE
Unable to activate twitter-5.16.0, because json-2.0.1 conflicts with json (~> 1.8)

### ISSUE THREAD

**Issue by jrobertson** [sferik/twitter#784]
Hello,

I recently updated my gems and now I can't run the Twitter gem because of the error message _Unable to activate twitter-5.16.0, because json-2.0.1 conflicts with json (~> 1.8)_. Please could you update the twitter.gemspec dependency to json version 2.0.1.

Thanks,

James Robertson

**Comment by ifonefox** [comment]
According to [1], this is because the "json dependency is in order to support older versions of Ruby."

[1] https://github.com/contentful/contentful.rb/issues/105#issuecomment-250615944
