### ISSUE TITLE
Can't disconnect from stream

### ISSUE THREAD

**Issue by AndrewHartAR** [sferik/twitter#785]
I have an array of Twitter Streaming Clients, and sometimes I'll wish to remove an existing stream, so I'll remove it from the array, but I've discovered this isn't stopping the stream itself, and so events are still coming through.

Is there something I'm missing - any way to stop it?

**Comment by ProjectDent** [comment]
I've posted this with more information here:
http://stackoverflow.com/questions/38252054/stream-with-yielding-function-is-being-kept-alive-after-removing-the-object-from

**Comment by stve** [comment]
I had been working on adding disconnect support, but I haven't found time to complete the work and the branch is fairly out of date at this point. e840e5f825df6b303ace6e8cf7387e2d011b801d

**Comment by ProjectDent** [comment]
This is my first Ruby project so likely wouldn't be able to complete it or re-do it.

Do you think there's a chance a more simple solution could be implemented?
