### ISSUE TITLE
Undefined method "update" for Twitter

### ISSUE THREAD

**Issue by Rui90** [sferik/twitter#787]
I created an initializer called twitter in my app with the following content:

```
$client = Twitter::Client.new do |config|
  config.consumer_key        = "mykey"
  config.consumer_secret     = "mykey"
  config.access_token        = "mykey-mykey"
  config.access_token_secret = "mykey"
end
```

Then I tried to make a call:

    $client.update("Fuck twitter!")

It did not work. `undefined method `update' for #<Twitter::Client:0x00000003f73610>`

Any idea why?

**Comment by stve** [comment]
Hi @Rui90,

`Twitter::Client` doesn't implement any API methods (it is primarily used by the REST and Streaming clients and adds so basic methods used by both). Can you change your code from `Twitter::Client` to `Twitter::REST::Client` to see if that helps.

Based on the initial title of this issue, you may be using an older version of the gem. Ensure you are using a recent release (5.x).

**Comment by Rui90** [comment]
@stve  that was exacly the problem. how dumb of me, thank you
