### ISSUE TITLE
equalizer dependency gem's incompatibility

### ISSUE THREAD

**Issue by jiggneshhgohel** [sferik/twitter#792]
I recently added following to my Gemfile:

```
gem 'twitter', '~> 5.16'
```

and ran command `$ bundle` and am facing incompatible gems error:

```
Bundler could not find compatible versions for gem "equalizer":
  In snapshot (Gemfile.lock):
    equalizer (= 0.0.11)

  In Gemfile:
    twitter (~> 5.16) was resolved to 5.16.0, which depends on
      equalizer (= 0.0.10)

    csv-importer was resolved to 0.3.1, which depends on
      virtus was resolved to 1.0.5, which depends on
        equalizer (>= 0.0.9, ~> 0.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

I have checked [virtus 1.0.5 gemspec](https://github.com/solnic/virtus/blob/v1.0.5/virtus.gemspec) and also its [master gemspec](https://github.com/solnic/virtus/blob/master/virtus.gemspec) and I don't think **virtus** has any plans for upgrading **equalizer's** version.

And the suggestion to run `bundle update` is not possible at this moment.

Is it necessary to use the exact version for **equalizer** in your gem? If that is the case then I think I will need to use an older version of gem which doesn't cause any incompatibility issues.

**Comment by maia** [comment]
This is related to #789.

**Comment by mvz** [comment]
@jiggneshhgohel have you tried `bundle update twitter equalizer`?

**Comment by jiggneshhgohel** [comment]
@mvz no. As a matter of fact the project on which I required this change is right now put on hold. And AFAIR I resolved my problem by using a older version of the gem.
