### ISSUE TITLE
Missing documentation for configuration with Rails

### ISSUE THREAD

**Issue by amingilani** [sferik/twitter#797]
While I understand this isn't a Rails gem, but it is used a lot with rails, and users (including myself and #449 ) are confused on how to get this working with Rails.

Some people bypass this by configuring the gem in `ApplicationController` (as in #185 ) and in the [sign-in-with-twitter app](https://github.com/sferik/sign-in-with-twitter/blob/master/app/controllers/application_controller.rb), but this violates the Skinny Controller convention. As well as moves configuration out of `config`

A method to load the gem in `config/intiializers` is described in [this blog](http://synaptian.com/2013/10/using-the-twitter-gem-in-your-rails-application/) but it is 3 years old, and I'm not certain if it will work.

**Comment by amingilani** [comment]
I can verify that the following configuration makes a global `Twitter` object available for use with the REST api

```
# config/initializers/twitter_client.rb
require 'twitter'

Twitter.configure do |config|
  config.consumer_key = ENV['TWITTER_CONSUMER_KEY']
  config.consumer_secret = ENV['TWITTER_CONSUMER_SECRET']
  config.oauth_token = ENV['TWITTER_ACCESS_TOKEN']
  config.oauth_token_secret = ENV['TWITTER_ACCESS_TOKEN_SECRET']
end
```

**Any ideas on how to get the streaming client working?**

**Comment by himberjack** [comment]
Why can't you just do:
```
$twitter = Twitter::Streaming::Client.new do |config|
  config.consumer_key        = ENV['twitter_key']
  config.consumer_secret     = ENV['twitter_secret']
  config.access_token        = ENV['twitter_at']
  config.access_token_secret = ENV['twitter_at_secret']
end
```

**Comment by amingilani** [comment]
@himberjack Because [Global Variables are Evil](https://programmers.stackexchange.com/questions/148108/why-is-global-state-so-evil), but also and more seriously, I'd get my pull request thrown out in the code review.

**Comment by himberjack** [comment]
I agree for most cases, however for a thread-safe lightweight HTTP Rest client - couldn't harm you.

**Comment by amingilani** [comment]
@himberjack but I would still have my code thrown out in the code review.

There are certainly ways to hack around this, like by creating a class in `lib/` that when required will give you a configured streaming client, but I'm almost certain there's already a way this has been implemented in the actual client itself.

**Comment by amingilani** [comment]
Ummm.. bump?

**Comment by mdesantis** [comment]
I would create a TwitterClient class in order to have a thread safe client:

```ruby
class TwitterClient
  def initialize
    Twitter::REST::Client.new do |config|
      config.consumer_key        = "YOUR_CONSUMER_KEY"
      config.consumer_secret     = "YOUR_CONSUMER_SECRET"
      config.access_token        = "YOUR_ACCESS_TOKEN"
      config.access_token_secret = "YOUR_ACCESS_SECRET"
    end
  end
end
```

and then in the controller or wherever you want:

```ruby
TwitterClient.new.update 'my wonderful tweet'
```

The same for the streaming client. How to organize / refactor up to you

**Comment by amingilani** [comment]
@mdesantis, quick question, should I save this class in `lib/` and require it in my `ApplicationController`? or would settings that up in `config/initializers/` ensure it's available everywhere?

**Comment by mdesantis** [comment]
Well everyone has its own way to include classes that are not models, controllers or views, pesonally I add `/lib` to the autoload paths so I can use it anywhere without need to require it:

```ruby
# in config/application.rb:

  [...]
  config.autoload_paths += %W(#{config.root}/lib)
  [...]
```

**Comment by stve** [comment]
Thanks to all that commented with ideas/suggestions. The reality is there is no single best practice and I'd be leery of suggesting one as it is unlikely to meet all use cases.
