### ISSUE TITLE
SON::ParserError in Accounts#index

### ISSUE THREAD

**Issue by Ginnelle** [sferik/twitter#802]
In my ruby program, have this error an  says 

**757: unexpected token at '≛歯崢਍'
Rails.root: c:/Sites/pruebadb**

Can anyone help me plz

**Comment by SagareGanesh** [comment]
@Ginnelle  can you please provide your code snippets or some more details of this error, so it will helpful for reproduce above error and resolve it. 

thanks

**Comment by jonmast** [comment]
I think this issue can be closed?

**Comment by stve** [comment]
I agree. @Ginnelle feel free to reopen if you have more information to share
