### ISSUE TITLE
Upcoming changes to tweets

### ISSUE THREAD

**Issue by aridlehoover** [sferik/twitter#809]
Is it possible to use this gem to submit links the way it is described in this article: https://dev.twitter.com/overview/api/upcoming-changes-to-tweets? Specifically, I'm looking for how I would append the hidden link metadata.

If so, how? If not, when?

**Comment by c0ri** [comment]
"Developers must avoid hard-coding length assumptions into their
applications." <-- this seems like a disaster. Not to mention the hidden
metadata. I am happy all the normal ppl and links won't count towards the
140 char limit, but maybe there's a better way to implement this.

C
