### ISSUE TITLE
Twitter::Error::BadRequest: Segments do not add up to provided total file size.

### ISSUE THREAD

**Issue by ericfontaine13** [sferik/twitter#811]
Hi,

I am pretty new at Ruby and I am trying to upload a clean mp4 video file (right audio and video codec) but unfortunately I always get this error when I am in the FINALIZE step. Here is my code:

```
file_path = "/Users/myfolder/myvideo.mp4"
filesize = File.open(file_path).size
media_id = init_request[:media_id]
base64_file = Base64.encode64(file_path).gsub("\n","")

init_request = Twitter::REST::Request.new(TWITTER, :post, "https://upload.twitter.com/1.1/media/upload.json",
  {"command" => "INIT",
   "total_bytes" => "#{filesize}",
   "media_type" => "video/mp4"
   }).perform

append_request = Twitter::REST::Request.new(TWITTER, :post, "https://upload.twitter.com/1.1/media/upload.json",
  {"command" => "APPEND",
   "media_id" => "#{media_id}",
   "media" => "#{file_path}",
   "media_data" => "#{base64_file}",
   "segment_index" => "1"
   }).perform

finalize_request = Twitter::REST::Request.new(TWITTER, :post, "https://upload.twitter.com/1.1/media/upload.json",
  {"command" => "FINALIZE",
   "media_id" => "#{media_id}"
   }).perform
```

I have worked on it for days and can't find the trick... If someone can lend me a hand. Thanks!

**Comment by sriti** [comment]
Hi 
We are getting the same error but intermittent. Where you able to fix the issue?

**Comment by Jsericks** [comment]
@ericfontaine13 @sriti 
I ran into this issue for a little and figured I'd help you out.
You cannot use the media_data: and the media: keys in the same post request. You'll need to send the base64 encoded chunk of the file as media_data, or alternatively send the file path as the media: value. If you send both I believe they cancel each other out.

`
      media = File.new(file_path)
      init = Twitter::REST::Request.new(@client, :post, MEDIA_UPLOAD_URL,
                                        { command: "INIT", media_type: "video/mp4",
                                          total_bytes: media.size }).perform
      until media.eof?
        base64_chunk = Base64.encode64(media.read(5_000_000))
        base64_chunk.delete("\n")
        seg ||= -1
        Twitter::REST::Request.new(@client, :post, MEDIA_UPLOAD_URL,
                                   { command: "APPEND", media_id: init[:media_id], media_data: base64_chunk,
                                     segment_index: seg += 1, key: :media }).perform
      end
      media.close
      Twitter::REST::Request.new(@client, :post, MEDIA_UPLOAD_URL,
                                 { command: "FINALIZE", media_id: init[:media_id] }).perform
`

**Comment by jasdeepkaur15** [comment]
@Jsericks 
I have implemented the same code as you suggested and this error is resolved. But now i am getting one another error. can you help me with this: 
[43] pry(#<SocialAccount>)> Twitter::REST::Request.new(client, :get, MEDIA_UPLOAD_URL,{
[43] pry(#<SocialAccount>)*     media_type: "video/mp4",command: "STATUS", media_id: init[:media_id], media_data: base64_chunk
[43] pry(#<SocialAccount>)* }).perform
**Errno::EPIPE: Broken pipe
from /home/vagrant/.rvm/rubies/ruby-2.3.6/lib/ruby/2.3.0/openssl/buffering.rb:322:in `syswrite'**
