### ISSUE TITLE
Looking up large quantity of users yields Thread error

### ISSUE THREAD

**Issue by mikeover** [sferik/twitter#812]
This occurs consistently when trying to lookup 25,000 users at once. As a workaround, I'm limiting to 1,000 per call and just concatenating them but I shouldn't have to do this.

can't create Thread: Resource temporarily unavailable
/app/vendor/bundle/ruby/2.2.0/gems/twitter-5.16.0/lib/twitter/utils.rb:39:in `initialize'
/app/vendor/bundle/ruby/2.2.0/gems/twitter-5.16.0/lib/twitter/utils.rb:39:in`new'
/app/vendor/bundle/ruby/2.2.0/gems/twitter-5.16.0/lib/twitter/utils.rb:39:in `block in pmap'
/app/vendor/bundle/ruby/2.2.0/gems/twitter-5.16.0/lib/twitter/utils.rb:39:in`each'
/app/vendor/bundle/ruby/2.2.0/gems/twitter-5.16.0/lib/twitter/utils.rb:39:in `each_slice'
/app/vendor/bundle/ruby/2.2.0/gems/twitter-5.16.0/lib/twitter/utils.rb:39:in`each'
/app/vendor/bundle/ruby/2.2.0/gems/twitter-5.16.0/lib/twitter/utils.rb:39:in `collect'
/app/vendor/bundle/ruby/2.2.0/gems/twitter-5.16.0/lib/twitter/utils.rb:39:in`pmap'
/app/vendor/bundle/ruby/2.2.0/gems/twitter-5.16.0/lib/twitter/utils.rb:25:in `flat_pmap'
/app/vendor/bundle/ruby/2.2.0/gems/twitter-5.16.0/lib/twitter/rest/users.rb:231:in`users'

**Comment by okeowosunday01** [comment]
i have the same problem while trying to search for up to 20,000 users at once on my mobile twitter app, but using the web browser and the desktop you can have a look at up to 25,000 users at once

**Comment by mf1crt** [comment]
If you try it on a different platform the issue should be resolved, I think the issue is with the mobile Twitter app. However on a web browser on desktops or even on mobile the issue seams to no longer exist.

**Comment by mikeover** [comment]
I'm not using a mobile app, I'm using a desktop web browser (safari).

**Comment by mf1crt** [comment]
Maybe the problem is because of safari i tried on google chrome

**Comment by mikeover** [comment]
Even if that is true, the issue should be investigated. Safari is a very popular browser and my workaround mentioned above works, but is significantly slower at looking the users up.

**Comment by mf1crt** [comment]
I agree, Twitters software developers should look in to this and resolve the issue.

**Comment by okeowosunday01** [comment]
i dont think the problem is from Twitters software developer, the only thing i think is that twitter app does not support multiple search of users account on mobile
