### ISSUE TITLE
Cannot retrieve text

### ISSUE THREAD

**Issue by GeorgeDewar** [sferik/twitter#813]
Using this gem, when I use `tweet_mode: "extended"`, it doesn't seem to correctly handle the tweet text. Without `tweet_mode: "extended"`, the output is as expected:

```
TwitterClient.status(788590358515032066).full_text
=> "RT @nznavy: OPEN SHIP || Anzac frigate HMNZS Te Mana is in Wellington this weekend &amp; will be open to the public on Saturday, 12… https://t.co/cZpsSACj3l"

JSON.parse(TwitterClient.status(788590358515032066).to_json)["text"]
=> "RT @nznavy: OPEN SHIP || Anzac frigate HMNZS Te Mana is in Wellington this weekend &amp; will be open to the public on Saturday, 12:30-4:30pm #…"
```

However, with it enabled I get the following:

```
TwitterClient.status(788590358515032066, tweet_mode: "extended").full_text
=> nil

JSON.parse(TwitterClient.status(788590358515032066, tweet_mode: "extended").to_json)["text"]
=> nil

JSON.parse(TwitterClient.status(788590358515032066, tweet_mode: "extended").to_json)["full_text"]
=> "RT @nznavy: OPEN SHIP || Anzac frigate HMNZS Te Mana is in Wellington this weekend &amp; will be open to the public on Saturday, 12:30-4:30pm #…"
```

It appears that `tweet_mode: "extended"` causes a `full_text` field to be provided instead of `text`, which breaks things.

**Comment by rusikf** [comment]
:+1: @GeorgeDewar but you can get text without working with JSON with extended mode:
```ruby
tweet.attrs[:full_text]
```

**Comment by dekaikiwi** [comment]
We're getting this issue too! Would be great to get #833 merged and released!

**Comment by chriso0710** [comment]
```tweet.attrs[:full_text]``` 
did not work for me. I am using
```tweet.attrs[:extended_tweet][:full_text]```

See #848
