### ISSUE TITLE
You have already retweeted this tweet. (Twitter::Error::Forbidden)

### ISSUE THREAD

**Issue by garalo** [sferik/twitter#818]
```ruby
tweets = client.user_timeline('xxxxxx ', count: 10, exclude: "retweets")
tweets.each { |tweet|
   #puts tweet.full_text
   puts "#{tweet.retweet_count} RT ====> #{tweet.full_text}"
   #if tweet.retweet_count == 0
      puts "---------->#{tweet.full_text}<------------"
      puts "Favorite: #{client.favorite(tweet)}"
      puts "Retweet: #{client.retweet(tweet)}"
 }
```
this is the simplest code and getting this error...
twitter-5.16.0/lib/twitter/rest/response/raise_error.rb:13:in `on_complete': You have already retweeted this tweet. (Twitter::Error::Forbidden)
What is the problem here?

**Comment by jonmast** [comment]
@garalo You're code snippet is impossible to read so it is difficult to debug. I suspect the issue is with `puts "Retweet: #{client.retweet(tweet)}"`, you are probably trying retweet a tweet that has already been retweeted.

**Comment by stve** [comment]
Per their docs, [if you've already retweeted, you cannot do so again](https://dev.twitter.com/rest/reference/post/statuses/retweet/id). Here's the gist of what's happening:

>Usage Notes:
>
> * This method is subject to update limits. A HTTP 403 will be returned if this limit as been hit.
> * Twitter will ignore attempts to perform duplicate retweets.

I'm not sure if this will work or not, but you could try to game the system by rescuing from `Twitter::Error::Forbidden`, unretweeting and then retweeting again. Twitter may still prevent against that implementation. It sounds like the update limit may allow what I've suggested but place additional restrictions around the number or frequency of retweets.

_caveat: It also may be against their policies, you'd have to check the documentation to see if it is permitted_

**Comment by garalo** [comment]
Ok. I think, I need  ..."retweet_count": 1,... before retweet?  Then how can I get this? Is there any example?

**Comment by stve** [comment]
I don't think there's an easy way to see if _you've_ already retweeted a tweet. It might be easiest to attempt to retweet and handle the error like I suggested above:

```ruby
tweets = client.user_timeline('xxxxxx ', count: 10, exclude: "retweets")
tweets.each do |tweet|
  begin
    client.retweet(tweet)
  rescue Twitter::Error::Forbidden
    begin
      client.unretweet(tweet)
      client.retweet(tweet)
    rescue Twitter::Error::Forbidden
      # either retweet or unretweet failed and there's no way to proceed
    end
  end
end
```

The code is kind of ugly but hopefully it makes sense what the intention is

**Comment by garalo** [comment]
Thank you.  Almost, What I want. But this code working only retweet. If I add another one client.favorite(tweet). I am getting error.
