### ISSUE TITLE
Count tweet Retweets?

### ISSUE THREAD

**Issue by acegilz** [sferik/twitter#822]
I am wondering how can I count how many retweets a specific tweet currently has.
Thanks

**Comment by stve** [comment]
Twitter provides the count through the API, so there's no need to count them yourself, look at  [`Twitter::Tweet#retweet_count`](http://www.rubydoc.info/gems/twitter/Twitter/Tweet#retweet_count-instance_method)

```ruby
tweet = client.status(27558893223)
tweet.retweet_count
#=> 123
```
