### ISSUE TITLE
Cryptic error messages on update_with_media emthod

### ISSUE THREAD

**Issue by andreitr** [sferik/twitter#830]
I am getting "_You cannot send messages to users who are not following you_" messages when using update_with_media method. Here's the code sample:

```
 begin
      result = client.update_with_media(tweet, file)
      rescue Twitter::Error::Forbidden => e
        raise "Twitter::Error::Forbidden #{e.message}."
      end
end
```

This is super strange since I am not sending any messages. The error is inconsistent and I don't see it most of the time. Any idea what might be the cause?

**Comment by andreitr** [comment]
As it turns out, the tweets that begin with an "M. " are treated like direct messages. More here [https://twittercommunity.com/t/getting-a-you-cannot-send-messages-when-posting-a-tweet/81373](url)

**Comment by stve** [comment]
👍 glad you were able to get to the bottom of it @andreitr
