### ISSUE TITLE
Upload video on 6x version

### ISSUE THREAD

**Issue by rusikf** [sferik/twitter#834]
Currently video upload is not working on 6x version, but works on current master

```ruby
Twitter::Error::BadRequest: media type unrecognized.
```

It looks, that on 6x version [update_with_media ](https://github.com/sferik/twitter/blob/6-stable/lib/twitter/rest/tweets.rb#L228)
changed, and on 6.x version it makes request to `/1.1/statuses/update_with_media.json` but it is [deprecated](https://dev.twitter.com/rest/reference/post/statuses/update_with_media)

**Comment by gowabash** [comment]
+1 - works in master, but not on version 6.1.  Is there an ETA for a new release?
