### ISSUE TITLE
I want to add Twitter Application Management link to the gem documentation.

### ISSUE THREAD

**Issue by tono0123** [sferik/twitter#836]
### Problem

I did not understand where to get consumer key.
There is no [Twitter Application Management link](https://apps.twitter.com/) in [this documentation](http://www.rubydoc.info/gems/twitter).
I have to go looking for other sites.

### Solution

After this sentence

```
Note: oauth_token has been renamed to access_token and oauth_token_secret is now access_token_secret to conform to the terminology used in Twitter's developer documentation.
```

Add the following sentences and links

```
"You can get the client key from [here](https://apps.twitter.com/)"
```

**Comment by alea12** [comment]
@tono0123 What you've mentioned seems to be present in [README.md](https://github.com/sferik/twitter/blob/master/README.md#configuration), in the "Configuration" part:

```markdown
## Configuration
Twitter API v1.1 requires you to authenticate via OAuth, so you'll need to
[register your application with Twitter][register]. Once you've registered an
application, make sure to set the correct access level, otherwise you may see
the error:

[register]: https://apps.twitter.com/
```

**Comment by tono0123** [comment]
I did not notice, thank you.

**Comment by alea12** [comment]
😇
