### ISSUE TITLE
Twitter::Error::TooManyRequests doesn't seem to have rate limits information anymore?

### ISSUE THREAD

**Issue by bobber205** [sferik/twitter#840]
Some of our clients accounts are oddly hitting rate limits when no tweets have been sent out from their handle > 12 hours.

I've tried debugging this by doing the following

```
      def post_dm(user_handle, dm_message)
        begin
          client.create_direct_message(user_handle, dm_message, {})
        rescue ::Twitter::Error::TooManyRequests => e
          puts "Oh shit here come dat error #{e.inspect}"
          puts "rate?"
          puts e.rate_limit.inspect
          puts e.rate_limit.limit
          puts e.rate_limit.remaining
          puts e.rate_limit.reset_at
          puts e.rate_limit.reset_in
          raise e
        end
      end
```

Everything after "rate?" is just blank lines.

What's up? Going from the documentation I don't _think_ these should be blank? Right?

Thanks for the reading!

**Comment by bobber205** [comment]
I'm now running

```
::Twitter::REST::Request.new(client, 'get', '/1.1/application/rate_limit_status.json').perform
```

and I don't see anything at its "limit". What should I look for exactly in that response?

**Comment by stve** [comment]
You _should_ expect rate limit data when you get `Twitter::Error::TooManyRequests`. I'll have to see why that is empty. 

Has this just started happening? Have you pinged Twitter to see if they've changed something with how rate-limits are imposed?

**Comment by DmitryKey** [comment]
hi!

Sorry to steal the thread, but getting the same error without specifying rate limit detail:

    /var/lib/gems/2.3.0/gems/twitter-6.1.0/lib/twitter/rest/response/raise_error.rb:13:in `on_complete': Rate limit exceeded (Twitter::Error::TooManyRequests)
