### ISSUE TITLE
:geocode param not returning results

### ISSUE THREAD

**Issue by mafellows** [sferik/twitter#841]
Hey there! Thanks a ton with the help on this great library. 

Noticed adding a :geocode parameter to a search isn't returning any results. 

``` 
client = Twitter::REST::Client.new do |config|
  # <keys>
end 

# Doesn't return any results. lat/lon is set to the Mountain View, CA area
client.search("google", geocode: "37.3849, -122.0819, 10mi")

# Returns results
client.search("google")
``` 

Anybody else noticing this issue?

**Comment by imechemi** [comment]
Yes, same here

**Comment by arjunmenon** [comment]
Was this resolved?

**Comment by andypiper** [comment]
This could be a simple case of a lack of geocoded Tweets for the area within the past seven days. Exact location was [removed from the main Twitter apps in mid-2019](https://twittercommunity.com/t/coordinates-field-in-tweet-objects/130372) and even with that feature, the number of users that actively choose to add geo information to their Tweets is generally very small.

**Comment by arjunmenon** [comment]
Nope, I verified a certain geocode with a python lib. I got the results.

**Comment by andypiper** [comment]
That’s good debugging info! Thanks for clarifying!
