### ISSUE TITLE
New way to update the timeout settings ?

### ISSUE THREAD

**Issue by ghost** [sferik/twitter#852]
Hi guys,
I keep running into the infamous `execution expired` issue, and according to https://github.com/sferik/twitter/issues/401 it looks like increasing the timeout fixes it, however I can't seem to find a way to do it using the new API ? 
Thanks,
Alvin

**Comment by JulioOrellana** [comment]
no one can answer this?

**Comment by waniss** [comment]
is there any answer for this issue please ?

**Comment by waniss** [comment]
@alvinsight, i found a solution:
Timeouts can be configured by passing a Hash to your configuration:
`timeouts = {:write => 5, :connect => 10,:read=>30}`
`client = Twitter::REST::Client.new do |config|
  config.consumer_key        = "YOUR_CONSUMER_KEY"
  config.consumer_secret     = "YOUR_CONSUMER_SECRET"
  config.access_token        = "YOUR_ACCESS_TOKEN"
  config.access_token_secret = "YOUR_ACCESS_SECRET"
  config.timeouts               =  timeouts
end`

check out [(https://github.com/sferik/twitter/blob/master/lib/twitter/rest/request.rb)] at line 120

**Comment by JulioOrellana** [comment]
Doesn't find timeouts method

![screen shot 2018-01-24 at 2 47 35 pm](https://user-images.githubusercontent.com/10372340/35348019-9434d46c-0115-11e8-8f33-cc7db02568b6.png)

**Comment by waniss** [comment]
Weird ! Make sure that you have the latest version of the twitter gem.

From the source code:
` client = client.timeout(:per_operation, connect: @client.timeouts[:connect], read: @client.timeouts[:read], write: @client.timeouts[:write]) if @client.timeouts`

It worked for me, the timeouts function does exists.

Try with timeout, maybe there is a conflict somewhere
