### ISSUE TITLE
options not work for get friends anymore

### ISSUE THREAD

**Issue by bianjingbulb** [sferik/twitter#853]
Hi, guys !
The option setting does not work for friends method.

There is my code.
```
options = {count: 8}
items = client.friends(options)
```

The result size is always 20.

What's wrong with this method?

**Comment by bianjingbulb** [comment]
Are there any ideas?

**Comment by craigthusiast** [comment]
Hi @stve, I'm finding the same problem with client.friends. The count option doesn't seem to work and I keep hitting the rate limit.

The count option also doesn't seem to work with the client.followers or the client.follower_ids methods.

Do these methods work for you with the count option?

Thanks!

**Comment by matthieu80** [comment]
hi @bianjingbulb and @craigthusiast, I have the same problem.

Did you find a solution?
for the following:
    @client.followers('screen_name', count: 200)
count is just ignored.

**Comment by craigthusiast** [comment]
@matthieu80 The count option still isn't working. However, I was able to avoid the problem by using the following method:
`search_results = client.followers(user).take(200)`
