### ISSUE TITLE
How to chech media type?

### ISSUE THREAD

**Issue by bianjingbulb** [sferik/twitter#855]
```
tweet.media.type
```
It doesn't work.

the type of tweet.media is just PHOTO? 
How can I check a media's type???

**Comment by dimstra** [comment]
If I get it right you just want to check whether the Tweet has any media and what type is it?
I managed to do this by using the `Entities`. Use `tweet.entities?` to check whether the the tweet has any kind of media.
If you just want to check for photos or videos you can user `tweet.media?`
All the other relative methods are:
```ruby 
tweet.hastags?
tweet.symbols?
tweet.uris?
tweet.user_mentions?
```
You can access those **entities*  by using the same methods without the question mark (?) like: 
`tweet.hashtags`

You check the [documentation](http://www.rubydoc.info/gems/twitter/Twitter/Entities) for more.
