### ISSUE TITLE
KeyError: key not found: "TWITTER_CONSUMER_KEY"

### ISSUE THREAD

**Issue by ldco2016** [sferik/twitter#871]
Greetings, 

I am using your gem for the first time and I did a: 

```
ENV.fetch("FAKE_TWITTER_CONSUMER_KEY")
KeyError: key not found: "FAKE_TWITTER_CONSUMER_KEY"
	from (irb):1:in `fetch'
	from (irb):1
```
to test the key and the expected behavior should have been "NOTMYREALKEY", instead I got the above. Even when I test my real key:

```
ENV.fetch("TWITTER_CONSUMER_KEY")
KeyError: key not found: "TWITTER_CONSUMER_KEY"
	from (irb):2:in `fetch'
	from (irb):2
```
I get the same error. Please advise.

I am passing the configuration as a block:

```
def self.twitter_search
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV.fetch("TWITTER_CONSUMER_KEY")
      config.consumer_secret     = ENV.fetch("TWITTER_CONSUMER_SECRET")
      config.access_token        = ENV.fetch("TWITTER_ACCESS_TOKEN")
      config.access_token_secret = ENV.fetch("TWITTER_ACCESS_SECRET")
    end
  end
```

inside a module.

I just want to be clear that I do have the dotenv-rails gem installed.

**Comment by Yaroslav-F** [comment]
It seems like your issue is simply not having `TWITTER_CONSUMER_KEY` environment variable defined. If you'll do `ENV` in the console - you'll probably see that it's missing.

Also it seems like this issue is not related to twitter gem and should go to stackoverflow instead.
