### ISSUE TITLE
Unable to access tweet text when using extended mode

### ISSUE THREAD

**Issue by nickshears** [sferik/twitter#872]
I need to use tweet_mode extended in order to access images for all tweets so I'm using the following code:

    `TWITTER_CLIENT.user_timeline(APP_CONFIG['twitter_user'], tweet_mode: "extended")`

Images are all being returned correctly, but when calling text/full_text on `Twitter::Tweet` it always returns a `Twitter::NullObject`.

**Comment by davehartnoll** [comment]
See #813
