### ISSUE TITLE
private method 'upload' called for Twitter::REST::Client

### ISSUE THREAD

**Issue by Yaroslav-F** [sferik/twitter#879]
Hi Erik,

Since when this method became private and called from Tweets module only?
It seems like the way to use it with Direct Messages had been lost.
Will change on my fork for now, but hope upload will either be added to DirectMessages or Media module will be brought back.

**Comment by shevegen** [comment]
Would .send() be possible for your case as a work around?

However had, I also totally understand having used some functionality that is changed; perhaps there is another way now to use the old method.

**Comment by Yaroslav-F** [comment]
Thanks @shevegen 
For now, as a workaround I use my fork of the gem where I moved `upload` method to `Twitter::REST::Utils` module. Needed to use my fork for webhooks anyway.
Might open a PR at some point, but seeing 27 unreviewed PRs here already is a bit discouraging 🙁

**Comment by jimmoffitt** [comment]
I hit this one today. Installed latest gem version 6.2.0, and it's throwing an error about calling the private 'upload' method... I really want to post a Tweet with a photo using the twitter gem...

**Comment by nhinze** [comment]
The gem handles the upload by itself using the update_with_media method. It does not use the deprecated Twitter API call. Change your code from:

```
    media_ids = images.map do |filename|
      Thread.new do
        client.upload(Twitter::Image.open_from_url(filename))
      end
    end.map(&:value)

    client.update('message', :media_ids => media_ids.join(',')')
```

to

```
    media = images.map do |filename|
      Thread.new do
        Twitter::Image.open_from_url(filename)
      end
    end.map(&:value)

    client.update_with_media('message', media)
```

My 'images' array is a list of URL paths to AWS S3 locations.

or as explained in the doc:

```
media = %w(/path/to/media1.png /path/to/media2.png).map { |filename| File.new(filename) }
client.update_with_media("I'm tweeting with @gem!", media)
```
