### ISSUE TITLE
[DEPRECATED] :mime_type option deprecated, use :content_type

### ISSUE THREAD

**Issue by JeffreyArtworks** [sferik/twitter#881]
```
		@social_product.images.first(4).each do |image|
			File.write "twitter#{@twitter_counter}.png", open(image.src).read
			@twitter_images << "./twitter#{@twitter_counter}.png"
			@twitter_counter = @twitter_counter + 1
		end
		@twitter_images = @twitter_images.map { |filename| File.new(filename) }
		@twitter_info = @twitter.update_with_media(@twitter_post, @twitter_images)
```

I am getting this "[DEPRECATED] :mime_type option deprecated, use :content_type" message every time I run the script. The tweet always goes through. Is there anything I need to fix to get rid of the warning?

**Comment by hmcfletch** [comment]
Looks like this option was deprecated here in [v1.0.2](https://github.com/httprb/form_data/blob/master/CHANGES.md#102-2017-05-08) of https://github.com/httprb/form_data. The changelog entry is [here](https://github.com/httprb/form_data/commit/5b902fab8d5b6493a400b2f82ac748d8ec0f25d3).

The changes to this gem would need to be made [here](https://github.com/sferik/twitter/blob/d7951759da897e6a8e3ed0069b2e850470991e3f/lib/twitter/rest/request.rb#L49-L52).

**Comment by Rybots** [comment]
##outside of def
　#when image is smaller than 10kb(image_path is recognized as a string by twitte)monkey patch
     module Twitter::Image
       def self.open_from_url(image_path)
         image_file = open(image_path)
         return image_file unless image_file.is_a?(StringIO)
         file_name = File.basename(image_path)
        temp_file = Tempfile.new(file_name)
        temp_file.binmode
        temp_file.write(image_file.read)
        temp_file.close
        open(temp_file.path)
      end
    end
##
 　　@social_product.images.first(4).each do |image|
	File.write "twitter#{@twitter_counter}.png", open(image.src).read
		@twitter_images << "./twitter#{@twitter_counter}.png"
		@twitter_counter = @twitter_counter + 1
	end
	@twitter_images = @twitter_images.map { |filename| File.new(filename) }

　　begin
	 @twitter_info = @twitter.update_with_media(@twitter_post, @twitter_images)
      rescue
          @twitter_images = Twitter::Image.open_from_url(@twitter_images)
          @twitter_info = @twitter.update_with_media(@twitter_post, @twitter_images)
      end

**Comment by astrolince** [comment]
When this gonna be merged?

**Comment by obiwankennedy** [comment]
No release have been made with this fix ? The version 6.2.0 still has this bug.

**Comment by ssrzz** [comment]
In my case, replacing .rvm/gems/ruby-2.5.1/gems/twitter-6.2.0/lib/twitter/rest/request.rb to [request.rb](https://raw.githubusercontent.com/ryanwi/twitter/b68ea1ad98e5a8814411011a0211feb30bff7f5b/lib/twitter/rest/request.rb) fixes the problem.

**Comment by mitchellkrogza** [comment]
Thank you @ssrzz that fixed it for me too :wink:

**Comment by mitchellkrogza** [comment]
> In my case, replacing .rvm/gems/ruby-2.5.1/gems/twitter-6.2.0/lib/twitter/rest/request.rb to [request.rb](https://raw.githubusercontent.com/ryanwi/twitter/b68ea1ad98e5a8814411011a0211feb30bff7f5b/lib/twitter/rest/request.rb) fixes the problem.

@GaoangLiu you dont perhaps have a copy of that request.rb that fixed this - this link has been deleted https://raw.githubusercontent.com/ryanwi/twitter/b68ea1ad98e5a8814411011a0211feb30bff7f5b/lib/twitter/rest/request.rb
