### ISSUE TITLE
Include support for quote_count and reply_count in the tweet object

### ISSUE THREAD

**Issue by bani** [sferik/twitter#895]
I wasn't able to access `quote_count` and `reply_count` when listing statuses from a timeline. They should be supported according to https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object

Can we add them here? https://github.com/sferik/twitter/blob/master/lib/twitter/tweet.rb#L12-L13

**Comment by jabrah29** [comment]
I can work on this :)

**Comment by andypiper** [comment]
These fields are only available in the premium and enterprise APIs, so you will not find them in a timeline Tweet object.
