### ISSUE TITLE
For the search, when the result_type  is "popular", count is ignored

### ISSUE THREAD

**Issue by ardaasln** [sferik/twitter#897]
I am using twitter `6.2.0`. I am getting 100 results in the following code snippet:

```  
options = {:result_type => "mixed", :count => 100}
result = @client.search(params, options)
```
For the following I am getting only 15 results which is the default count:

```  
options = {:result_type => "popular", :count => 100}
result = @client.search(params, options)
```
Why "popular" attribute is ignoring the count?

**Comment by andypiper** [comment]
It's a bug in the Twitter standard Search API. "popular" only ever supports a maximum of 15 results. Other options ("mixed" and "recent") support up to 100 at a time.

**Comment by ardaasln** [comment]
I have actually managed to fetch 100 "popular" tweets via [npm library](https://www.npmjs.com/package/twitter) in my NodeJS app. I thought it has something to do with this particular ruby library.
