### ISSUE TITLE
Gem still not fully compatible with new extended tweets

### ISSUE THREAD

**Issue by chriso0710** [sferik/twitter#905]
I am using this gem together with Twitters streaming API. It has been working great for some years now. 

Twitter made some rather big changes in the last couple of months with 280 chars, extended tweets, etc. and I fully understand that it's not easy to keep up with these changes and maintain the gem.

I successfully did a workaround for full_text (see #848).
I was having problems with media data. With extended tweets and the streaming API the gem is not able to get and create the corresponding media objects, as they are not inside the "old" hash. IMHO the problem is here

https://github.com/sferik/twitter/blob/aa909b3b7733ca619d80f1c8cba961033d1fc7e6/lib/twitter/entities.rb#L33

and I made a workaround for that too. There must be more users of this gem, who are also struggling with changes and creating their own patches/workarounds.

After looking into the issues, the code and at the open pull requests, it seems to me that this gem is slowly falling behind in supporting the new extended tweets. I might of course be mistaken. But are there any plans to update the gem and/or merge open (new and old) pull requests?

Christian

**Comment by bobber205** [comment]
From what I've been told on the forums is that this gem is considered in minimal maintenance mode only. No further updates are planned. :\ They're focusing on NodeJS now.

**Comment by maia** [comment]
@bobber205 Thanks for the info. I wonder if someone from the community could pick up the maintenance of this gem.
