### ISSUE TITLE
Rest and Stream APIs are sunsetting by June 19, 2018

### ISSUE THREAD

**Issue by venkat20390** [sferik/twitter#908]
Twitter plans to sunset the REST and Stream APIs on Tuesday June 19, 2018. I could see this gem is being heavily relied on them. Will this gem work even after June 19,2018? Can we rely on creating new Twitter bots using this gem now?

**Comment by clarkbab** [comment]
As above, we rely heavily on the `direct_messages` endpoints and would like to know if there is any plan for updating this gem to use the new `direct_messages/events` endpoints?

**Comment by boncey** [comment]
Is there a link to support the bit about the REST API being turned off?
I [saw something](https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html) about switching off streaming and direct messaging endpoints but not REST as a whole.

Thanks.

**Comment by andypiper** [comment]
The overall REST API endpoints are not going away. The specific endpoints that are being sunset (and replaced with new, more advanced alternatives) are the Direct Message REST endpoints.

**Comment by brandonhilkert** [comment]
@sferik Thanks for https://github.com/sferik/twitter/commit/0833471366a33657cd2920850e3928db010eecab. Any chance it'll be released soon?
