### ISSUE TITLE
Debugging old get_all_tweets call

### ISSUE THREAD

**Issue by jahrichie** [sferik/twitter#909]
Debugging an older app that requested the last 51 tweets from kanyewest...don't ask.   This was working great but is getting authenication errors now and all the creds match correctly.  Has Twitter disabled this part of the api/auth? Any leads is appreciated. 

```
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = "CENSORED"
      config.consumer_secret     = "CENSORED"
      config.access_token        = "CENSORED"
      config.access_token_secret = "CENSORED"
    end    

  per_page = 51
  handle   = 'kanyewest'
  # @tweets = client.get_all_tweets("kanyewest")
  options = {count: per_page, include_rts: false}
  @tweets = client.user_timeline(handle,options)
```

**Comment by nathanKramer** [comment]
Stupid question, but have you got the `get_all_tweets` method on your `client`? It needs to be added in as per the example:

https://github.com/sferik/twitter/blob/master/examples/AllTweets.md

The implementation in the example seems to work for me.
