### ISSUE TITLE
get followers with :count option

### ISSUE THREAD

**Issue by matthieu80** [sferik/twitter#915]
Here is how I try to fetch a specific number of followers:
@client.followers('screen_name', count: 50)
the count option is ignored.

Any idea?
Thank you

**Comment by matthieu80** [comment]
I gave up the "followers" method.
I use "follower_ids", then the "lookup" one.
It is more flexible, and the rate limit is harder to reach, so only benefits.
@duncangarde, maybe the "friend_ids" method will help you out?

**Comment by duncangarde** [comment]
@matthieu80 thanks! Yeah I have moved to that and it works. Appreciate it.

D
