### ISSUE TITLE
Is there a recommended workflow for gathering all the credentials less manually?

### ISSUE THREAD

**Issue by hakanai** [sferik/twitter#920]
The current workflow more or less requires 4 magic values to be known in order to use the client (the application I'm writing requires access to the user's home timeline, so to show tweets from protected users I do have to authenticate the user as well):

```
client = Twitter::REST::Client.new do |config|
  config.consumer_key        = "YOUR_CONSUMER_KEY"
  config.consumer_secret     = "YOUR_CONSUMER_SECRET"
  config.access_token        = "YOUR_ACCESS_TOKEN"
  config.access_token_secret = "YOUR_ACCESS_SECRET"
end
```

If I follow the docs as they currently read, it seems like I'd be asking the user to go and dig these out for themselves for every new user who starts the application. First they have to go to register themselves an application, because I presumably can't just ship the secret with my application. Then the process for getting the other two values is actually unclear. The docs link to the REST docs at Twitter, which leads me to believe this is still missing from the Ruby API.

So I'm wondering if anyone has sorted out a more straightforward way to use this yet. From a usability standpoint, I don't really want my users to have to go through all that garbage just to login, if there is an alternative where perhaps they can just use their username and password, like with any other client I use currently.

**Comment by hkmaly** [comment]
I'm afraid that with the application keys, your only options are to put the secrets in application or let user register the application themselves.

However, the access_token and access_token_secret should be possible to obtain automatically, at least if your application is on web. I have no idea why this gem doesn't contain support for this, I was just looking for it.

**Comment by hkmaly** [comment]
Related  #609 recommends using another gem.

**Comment by hkmaly** [comment]
(Note that lot of those alternative gems are huge with lot of dependencies. The "oauth" seem to be only sane one.)

**Comment by andypiper** [comment]
There’s a sample app [here](https://github.com/twitterdev/sign_in_with_twitter_sample) which shows how you can achieve Sign-in With Twitter in Ruby with the OAuth gem.
