### ISSUE TITLE
New 6.3.0 version?

### ISSUE THREAD

**Issue by FabienChaynes** [sferik/twitter#933]
Hello @sferik,

First of all, thanks for your latest work on the gem :slightly_smiling_face: 

The last gem version release is the [6.2.0](https://rubygems.org/gems/twitter/versions/6.2.0) from November 08, 2017 and is 23 commits behind master.

I'd like to know if you plan to publish a new gem version? If something is holding you back, is there anything we can do to help?

Thanks!

**Comment by GauthamSakthiveeran** [comment]
FabienChaynes : is there a way i can send Direct Messages with Twitter Gem 5.16 using,
 response = Twitter::REST::Request.new(@client, :post, '/1.1/direct_messages/events/new.json', options).perform

Can you please help me on this...

**Comment by bobber205** [comment]
I'm pretty sure they've abandoned this project.

**Comment by chriso0710** [comment]
@sferik Is there a chance that a group of interested people from the community might pick up the maintenance of this gem?
