### ISSUE TITLE
Question: Retrieve User Email

### ISSUE THREAD

**Issue by SylarRuby** [sferik/twitter#943]
Is it possible to retrieve a user email address from the user model? I see the screen_name and uri but no mention of the email. This is all assumed that the consumer has permission to get the user email. 

Thanks

**Comment by andypiper** [comment]
You'd need to call the [`account/verify_credentials` endpoint](https://developer.twitter.com/en/docs/accounts-and-users/manage-account-settings/api-reference/get-account-verify_credentials.html) with the `include_email=true` option on the API.

**Comment by SylarRuby** [comment]
Thanks! Just got back with this so sorry for the late reply.
