### ISSUE TITLE
How to use properly create_direct_message ?

### ISSUE THREAD

**Issue by alex-thp** [sferik/twitter#947]
Hi ! I'm trying to use your function but I meet a problem... Here it is :

/home/a1/.rvm/gems/ruby-2.5.1/gems/twitter-6.2.0/lib/twitter/rest/request.rb:81:in `fail_or_return_response_body': Sorry, that page does not exist. (Twitter::Error::NotFound)

And here is my code :
client.create_direct_message(1447374817, "Salut, dis moi si ça fonctionne stp !")

1447374817 is the user ID of the target. If you know what is going wrong, I'd be glad if you'd tell me !

Thanks,
Alex

**Comment by tristang** [comment]
This is related to #908. In [this post](https://github.com/sferik/twitter/issues/908#issuecomment-401881214) it looks like an update is on the way but I'm not sure when.

**Comment by alex-thp** [comment]
Thanks !
