### ISSUE TITLE
No such file or directory @ rb_sysopen, using upload_with_media method

### ISSUE THREAD

**Issue by kraizel** [sferik/twitter#951]
I'm trying to tweet an image with its status, however, i'm getting this error everytime i try to. I've tried everything and still cannot figure what's occasioning the error. I'm using carrierwave to process the images.

### Current call
      @tweet = twitter.update_with_media('status' , File.open(@donation.images.first.picture.to_s) )
### Error
No such file or directory @ rb_sysopen - /uploads/image/picture/74/banner5.png <- That's the image i'm trying to upload

**Comment by PashaLVWD** [comment]
Has nothing to do with Twitter gem. Error is coming from `File.open`

```
2.4.2 :029 >   File.open('/tmp/picture.png')
Errno::ENOENT: No such file or directory @ rb_sysopen - /tmp/picture.png
	from (irb):29:in `initialize'
	from (irb):29:in `open'
	from (irb):29
2.4.2 :030 >
```

**Comment by kraizel** [comment]
Yes, sorry. I've already figured it out what was wrong with my code. Thanks, anyway!

**Comment by siddhartharun** [comment]
@rt-garcia Can you share your solution? I'm stuck with the same problem.
