### ISSUE TITLE
Call for new maintainers for this project

### ISSUE THREAD

**Issue by ajsharp** [sferik/twitter#952]
I don't know any better place to post this so I'm posting here. It seems that this project is [largely unmaintained](https://github.com/sferik/twitter/issues/905#issuecomment-415194226) and has fallen behind with major twitter API changes (see #905 #813 #880).

Is there any desire amongst the current maintainers @sferik et al to find new maintainers amongst the community? 

If not, is there desire amongst users of this project to fork this into a new project with a new name (so as to avoid confusion)?

**Comment by dekaikiwi** [comment]
Would be really keen to see this project maintained perhaps by a group to avoid the situation we currently find ourselves in.

Not sure if I have the experience to head up the entire operation, but would be keen to work together with someone if there is interest!

**Comment by ajsharp** [comment]
Thanks @dekaikiwi. I'm focused on another project for the next few days, but after that I'll be back to using this. For me, the main goals of forking this project would be to keep up with recent(ish) twitter api changes.

Beyond that, I think it's worth discussing more broadly what users of this library would like from it going forward. I have a few gripes with it, such as lack of access to the raw response object and headers (useful for managing rate limits), but that's just me. I'm interested in hearing what others would like from it.

**Comment by tomholford** [comment]
Any updates on this? There are some great updates coming to the API that should be considered for inclusion in this gem:

https://developer.twitter.com/en/docs/labs/overview/whats-new/formats-expansions

**Comment by ajsharp** [comment]
@tomholford I'm willing to spearhead a new project / fork unless @sferik or any of the current maintainers are interested in adding maintainers to this one.

**Comment by tylerklose** [comment]
@ajsharp @tomholford any idea how much effort is needed to get a new project / a fork of this project up to speed with the new changes?

**Comment by ajsharp** [comment]
@tylerklose probably not much to get the project set up. I think the way to move forward is to fork this project with a new project name, to clearly differentiate from this project, which will reduce confusion of future people looking for an actively maintained twitter library.

In terms of the changes needed, I'm not sure. There are some structural things about this library that I'm not wild about, for example, not being able to get access to the raw response objects to inspect headers for things like rate-limiting. Still, this project is pretty solid, and I certainly wouldn't want to start fresh with a new library.

If you're interested in contributing, I'm happy to lead the effort by forking a new project with a new name. Maybe, twitter2?

**Comment by tylerklose** [comment]
@ajsharp I don't want to overcommit, but I am willing to help as I can. `twitter2` seems like a reasonable name or something like `twitter-client` could do the trick. Let me know how I can be helpful!

**Comment by andreitr** [comment]
I am with @tylerklose, I don't want to overcommit but I am happy to contribute. I've implemented the Labs Metrics endpoint in my own code and happy to push it into the main project.

**Comment by tomholford** [comment]
Similar to @andreitr, I implemented the [Labs Get Tweets V1](https://developer.twitter.com/en/docs/labs/tweets-and-users/api-reference/get-tweets-v1) call, and would also be happy to contribute it to a new project.

**Comment by tomholford** [comment]
Hey all, with the release of the new v2 endpoints, I took a moment to put together a basic client implementation here:

https://github.com/tomholford/twitter-labs-api

Contributions welcome :) Hope this helps everyone prepare for the deprecation of the v1 endpoint in ~83 days.

**Comment by sbleon** [comment]
18 months later, there doesn't appear to be a clear successor to this gem, or any new maintainers for this gem. Are people still using this gem? Is anyone reliant on it enough to want to become a maintainer?

**Comment by andypiper** [comment]
I've seen [this gem](https://github.com/julianfssen/tweetkit) for v2.

**Comment by jtoy** [comment]
that gem looks dead as well. It seems twitter for ruby is dead. In python there are active projects though!
