### ISSUE TITLE
Twitter::Client#blank? conflicts with rails #blank? and #present?

### ISSUE THREAD

**Issue by matteeyah** [sferik/twitter#960]
`Twitter::Client#blank?` conflicts with the usage of rails `#blank?` and `#present?`.

It should be renamed to something else that's ambiguous and not used in rails.

**Comment by sferik** [comment]
What’s the actual issue here? This is a `private` method, so it shouldn’t conflict.

**Comment by matteeyah** [comment]
I wish I explained this better at the time of opening. I can't seem to remember what it conflicted with exactly, but I'm 100% positive that it somehow had a negative impact to the usability of this gem (otherwise I wouldn't have opened it).
