### ISSUE TITLE
support httprb gem 4.x/5.x

### ISSUE THREAD

**Issue by jrochkind** [sferik/twitter#964]
The `http` (httprb) gem is [up to a 4.2.0 release. 4.0.0 was released in Oct 2018](https://rubygems.org/gems/http/versions). In fact, a 5.0.0pre release is out. 

However, this gem's [gemspec restricts](https://github.com/sferik/twitter/blob/844818cad07ce490ccb9d8542ebb6b4fc7a61cb4/twitter.gemspec#L9) to `http` 3.x. 

That means any project that depends on this gem can only use http 3.x, not the newer http 4.x or upcoming 5.x. 

Could the twitter gem be updated to use/allow more recent `http` releases?

Is this `twitter` gem currently maintained? Thanks!

**Comment by jrochkind** [comment]
I do unfortunately seem to have run into a bug in http that is only fixed in 4.2.0, so being stuck on 3.x, I am stuck on bug effecting me. 

Don't know exactly why but:

   HTTP.get("https://tenderlovemaking.com/atom.xml").to_s

With httprb 4.2.0 returns body as expected, in any previous httprb returns an incorrect empty string. Some bug that URL response specifically triggers, apparently.  My app is trying to fetch that particular URL. So unable to upgrade to `http` 4.2.0 because of dependency on the `twitter` gem, which requires only 3.x -- my app is unable to use `http` gem to fetch it. :(

Any feedback from maintainers appreciated!

**Comment by FireFart** [comment]
Same here. http 4.3 fixed some compatibility issues with ruby 2.7 and the twitter gem is preventing other gems to use this new version

**Comment by jrochkind** [comment]
Would it make sense for me to try to prepare a PR loosening up `http` dependency restrictions?  

Any feedback from maintainers? @sferik ?

**Comment by excid3** [comment]
I [forked the gem](https://github.com/excid3/twitter) because I ran into the same thing. 

The only thing I had to change for http 4.x support was the timeout method call. I also updated bundler dependency for development to allow 2.x. 

All the tests passed, so it looks good and should be an easy enough upgrade when http 5.x comes out.

**Comment by jrochkind** [comment]
Thanks @excid3 !

It's looking to me like the ruby twitter API client gem is effectively unmaintained/abandoned? @sferik ?

I will probably use @excid3's fork, while I consider if I can get off twitter gem entirely, just use raw HTTP to interact with twitter API I guess?

**Comment by FireFart** [comment]
I only needed tweet functionality so I switched to a self implementation. Feel free to copy it if you need it too

```ruby
module Twitter
  # code from https://developer.twitter.com/ja/docs/basics/authentication/guides/single-user
  class << self
    def send_tweet(tweet)
      response = client.post('https://api.twitter.com/1.1/statuses/update.json', status: tweet, trim_user: true)
      raise "Status code is not 200! #{response.code} #{response.body}" if response.code != '200'
    end

    private

    def client
      @client ||= create_client
    end

    def create_client
      consumer = OAuth::Consumer.new(ENV['TWITTER_CONSUMER_KEY'], ENV['TWITTER_CONSUMER_SECRET'], site: 'https://api.twitter.com', scheme: :header)
      token_hash = { oauth_token: ENV['TWITTER_ACCESS_TOKEN'], oauth_token_secret: ENV['TWITTER_ACCESS_TOKEN_SECRET'] }
      OAuth::AccessToken.from_hash(consumer, token_hash)
    end
  end
end
```

**Comment by jrochkind** [comment]
See also https://github.com/yhara/simple_twitter
