### ISSUE TITLE
Twitter Stream Follow limits

### ISSUE THREAD

**Issue by brusacco** [sferik/twitter#972]
Hello,
I have a stream listening to many TW accounts:
client.filter(follow: follow) do |tweet|

The follow is a long string of 1246 TW users id's. The problem is that I can't add another ID to the list, after that the stream never starts anymore.

So when I add one more, 1247 ... the streams gets stalled. TW DOC's says that we can "follow" up to 5000 ids's, so it's no an API limit problem.

Any clues here?

Thanks.

**Comment by brusacco** [comment]
Any updates on this? Anyone that follow more that 1500 accounts, like 2000 or 3000?
Thanks

**Comment by lemig** [comment]
@brusacco This is fixed in this pull request
https://github.com/sferik/twitter/pull/996

**Comment by sferik** [comment]
@lemig I merged this patch but had to revert it because it broke the tests. Please let me know if you’d like to rework this patch to fix the tests before the next release, which I’m preparing now.
