### ISSUE TITLE
Unable to retrieve rate limit info from Twitter::REST::Tweets.update

### ISSUE THREAD

**Issue by thibauds** [sferik/twitter#977]
I would like to be able to get rate limit info after calling `Twitter::REST::Tweets.update`.
I am able to get it on rate limit error but would like to get it before hitting the limit.
If it is not available, would you accept a PR exposing headers on `Twitter::REST::*` methods?

**Comment by andypiper** [comment]
There is no API-provided rate limit for posting Tweets. These are account-level limits (see [here](https://help.twitter.com/en/rules-and-policies/twitter-limits)). Unfortunately this means that you need to do your own manual counting in code, there's no header or endpoint that can help you.
