### ISSUE TITLE
HTTP::ConnectionError: failed to connect: Connection reset by peer - SSL_connect

### ISSUE THREAD

**Issue by wonderer007** [sferik/twitter#992]
I am trying to upload a video file (in development mode), I often get this error while uploading video file

```
HTTP::ConnectionError: failed to connect: Connection reset by peer - SSL_connect
```

My assumption is this error won't occur in production when I have SSL.

**Comment by datakid** [comment]
I'm seeing a lot of `#<HTTP::ConnectionError: error reading from socket: Connection reset by peer>` so maybe it's deeper?
